id: AccelEnrich.panel
description: Accel/Decel Enrichment
source:
  ini_dialog: AccelEnrich
  menu_path: Fuel › TPS Acceleration Enrichment / Wall Wetting AE › Acceleration enrichment
children:
- type: section
  props:
    title: TPS
  children:
  - type: enum-field
    id: accelenrichmentmode
    props:
      options:
      - value: 0
        label: MS Adder
      - value: 1
        label: Percent Adder
      - value: 2
        label: MAP Prediction
      - value: 3
        label: INVALID
      label: Accel Enrichment Mode
    bind:
      source: config
      field: accelEnrichmentMode
  - type: enum-field
    id: istuningdetectorenabled
    props:
      label: Detect Tuning and Suspend
      options:
      - value: 0
        label: no
      - value: 1
        label: yes
    bind:
      source: config
      field: isTuningDetectorEnabled
  - type: text
    props:
      variant: hint
      text: '"" ; spacer'
  - type: scalar-field
    id: tpsaccellookback
    props:
      label: Length
    bind:
      source: config
      field: tpsAccelLookback
  - type: scalar-field
    id: nofueltrimafteracceltime
    props:
      label: Inhibit closed loop fuel after accel
    bind:
      source: config
      field: noFuelTrimAfterAccelTime
  - type: scalar-field
    id: tpsaccelenrichmentthreshold
    props:
      label: Accel Activation Threshold
    bind:
      source: config
      field: tpsAccelEnrichmentThreshold
  - type: scalar-field
    id: tpsdecelenleanmentthreshold
    props:
      label: Decel Threshold
    bind:
      source: config
      field: tpsDecelEnleanmentThreshold
  - type: text
    props:
      variant: hint
      text: 'Accelerator Pump model:'
  - type: scalar-field
    id: tpsaccelfractionperiod
    props:
      label: Fraction Period
    bind:
      source: config
      field: tpsAccelFractionPeriod
- type: section
  props:
    title: Wall Wetting
  children:
  - type: enum-field
    id: complexwallmodel
    props:
      options:
      - value: 0
        label: Basic (constants)
      - value: 1
        label: Advanced (tables)
      label: Wall fueling model type
    bind:
      source: config
      field: complexWallModel
  - type: scalar-field
    id: wwaetau
    props:
      label: evaporation time constant / tau
    bind:
      source: config
      field: wwaeTau
  - type: scalar-field
    id: wwaebeta
    props:
      label: added to wall coef / beta
    bind:
      source: config
      field: wwaeBeta
- type: text
  props:
    variant: hint
    text: Панель «AccelEnfichIndicatorsPanel» — нет определения в INI
