id: acSettings.panel
description: Air Conditioning
source:
  ini_dialog: acSettings
  menu_path: Setup › Limits and protection › Air Conditioning
children:
- type: section
  props:
    title: A/C Settings
  children:
  - type: enum-field
    id: acswitch
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: INVALID
      - value: 2
        label: Analog Volt 5
      - value: 3
        label: Analog Volt 6
      - value: 4
        label: Analog Volt 7
      - value: 5
        label: Analog Volt 8
      - value: 6
        label: Analog Volt 9
      - value: 7
        label: Analog Volt 10
      - value: 8
        label: Analog Volt 11
      - value: 9
        label: INVALID
      - value: 10
        label: INVALID
      - value: 11
        label: INVALID
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: Analog Temp 3
      - value: 19
        label: Analog Temp 4
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      - value: 32
        label: INVALID
      - value: 33
        label: INVALID
      - value: 34
        label: Analog Volt 1
      - value: 35
        label: Analog Volt 2
      - value: 36
        label: Analog Volt 3
      - value: 37
        label: Analog Volt 4
      - value: 38
        label: Analog Temp 1
      - value: 39
        label: Analog Temp 2
      - value: 40
        label: Digital 1
      - value: 41
        label: INVALID
      - value: 42
        label: INVALID
      - value: 43
        label: INVALID
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: INVALID
      - value: 54
        label: INVALID
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: INVALID
      - value: 58
        label: INVALID
      - value: 59
        label: INVALID
      - value: 60
        label: INVALID
      - value: 61
        label: INVALID
      - value: 62
        label: INVALID
      - value: 63
        label: INVALID
      - value: 64
        label: INVALID
      - value: 65
        label: INVALID
      - value: 66
        label: INVALID
      - value: 67
        label: INVALID
      - value: 68
        label: INVALID
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: Digital 2
      - value: 78
        label: Digital 3
      - value: 79
        label: Digital 5
      - value: 80
        label: Digital 4
      - value: 81
        label: Digital 6
      - value: 82
        label: INVALID
      - value: 83
        label: INVALID
      - value: 84
        label: INVALID
      - value: 85
        label: INVALID
      - value: 86
        label: INVALID
      - value: 87
        label: INVALID
      - value: 88
        label: INVALID
      - value: 89
        label: INVALID
      - value: 90
        label: INVALID
      - value: 91
        label: INVALID
      - value: 92
        label: INVALID
      - value: 93
        label: INVALID
      - value: 94
        label: INVALID
      - value: 95
        label: INVALID
      - value: 96
        label: INVALID
      - value: 97
        label: INVALID
      - value: 98
        label: INVALID
      - value: 99
        label: INVALID
      - value: 100
        label: INVALID
      - value: 101
        label: INVALID
      - value: 102
        label: INVALID
      - value: 103
        label: INVALID
      - value: 104
        label: INVALID
      - value: 105
        label: INVALID
      - value: 106
        label: INVALID
      - value: 107
        label: INVALID
      - value: 108
        label: INVALID
      - value: 109
        label: INVALID
      - value: 110
        label: INVALID
      - value: 111
        label: INVALID
      - value: 112
        label: INVALID
      - value: 113
        label: INVALID
      - value: 114
        label: INVALID
      - value: 115
        label: INVALID
      - value: 116
        label: INVALID
      - value: 117
        label: INVALID
      - value: 118
        label: INVALID
      - value: 119
        label: INVALID
      - value: 120
        label: INVALID
      - value: 121
        label: INVALID
      - value: 122
        label: INVALID
      - value: 123
        label: INVALID
      - value: 124
        label: INVALID
      - value: 125
        label: INVALID
      - value: 126
        label: INVALID
      - value: 127
        label: INVALID
      label: A/C switch
    bind:
      source: config
      field: acSwitch
  - type: enum-field
    id: acswitchmode
    props:
      options:
      - value: 0
        label: DEFAULT
      - value: 1
        label: PULLUP
      - value: 2
        label: PULLDOWN
      - value: 3
        label: INVALID
      - value: 4
        label: INVERTED DEFAULT
      - value: 5
        label: INVERTED PULLUP
      - value: 6
        label: INVERTED PULLDOWN
      - value: 7
        label: '"INVALID'
      label: A/C switch mode
    bind:
      source: config
      field: acSwitchMode
  - type: enum-field
    id: acrelaypin
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: INVALID
      - value: 2
        label: INVALID
      - value: 3
        label: INVALID
      - value: 4
        label: INVALID
      - value: 5
        label: INVALID
      - value: 6
        label: INVALID
      - value: 7
        label: INVALID
      - value: 8
        label: INVALID
      - value: 9
        label: INVALID
      - value: 10
        label: Highside 2
      - value: 11
        label: Highside 1
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: Lowside 8
      - value: 23
        label: Lowside 9
      - value: 24
        label: Lowside 10
      - value: 25
        label: Lowside 11
      - value: 26
        label: Lowside 12
      - value: 27
        label: Lowside 13
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      - value: 32
        label: INVALID
      - value: 33
        label: INVALID
      - value: 34
        label: INVALID
      - value: 35
        label: INVALID
      - value: 36
        label: INVALID
      - value: 37
        label: INVALID
      - value: 38
        label: INVALID
      - value: 39
        label: INVALID
      - value: 40
        label: INVALID
      - value: 41
        label: Ign 5
      - value: 42
        label: Ign 4
      - value: 43
        label: Ign 3
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: Ign 2
      - value: 54
        label: Ign 1
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: Lowside 1
      - value: 58
        label: STM32 PD8
      - value: 59
        label: STM32 PD9
      - value: 60
        label: STM32 PD10
      - value: 61
        label: STM32 PD11
      - value: 62
        label: STM32 PD12
      - value: 63
        label: STM32 PD13
      - value: 64
        label: Highside 4
      - value: 65
        label: Highside 3
      - value: 66
        label: Lowside 14 or starter
      - value: 67
        label: Lowside 15
      - value: 68
        label: Lowside 16
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: INVALID
      - value: 78
        label: INVALID
      - value: 79
        label: INVALID
      - value: 80
        label: INVALID
      - value: 81
        label: INVALID
      - value: 82
        label: INVALID
      - value: 83
        label: INVALID
      - value: 84
        label: INVALID
      - value: 85
        label: INVALID
      - value: 86
        label: INVALID
      - value: 87
        label: INVALID
      - value: 88
        label: INVALID
      - value: 89
        label: INVALID
      - value: 90
        label: INVALID
      - value: 91
        label: INVALID
      - value: 92
        label: INVALID
      - value: 93
        label: INVALID
      - value: 94
        label: INVALID
      - value: 95
        label: INVALID
      - value: 96
        label: INVALID
      - value: 97
        label: INVALID
      - value: 98
        label: INVALID
      - value: 99
        label: INVALID
      - value: 100
        label: Ign 12
      - value: 101
        label: Ign 11
      - value: 102
        label: Ign 10
      - value: 103
        label: Ign 9
      - value: 104
        label: Ign 8
      - value: 105
        label: Ign 7
      - value: 106
        label: Ign 6
      - value: 107
        label: Lowside 2
      - value: 108
        label: Lowside 3
      - value: 109
        label: Lowside 4
      - value: 110
        label: Lowside 5
      - value: 111
        label: Lowside 6
      - value: 112
        label: Lowside 7
      - value: 113
        label: INVALID
      - value: 114
        label: INVALID
      - value: 115
        label: INVALID
      - value: 116
        label: INVALID
      - value: 117
        label: INVALID
      - value: 118
        label: INVALID
      - value: 119
        label: INVALID
      - value: 120
        label: INVALID
      - value: 121
        label: INVALID
      - value: 122
        label: INVALID
      - value: 123
        label: INVALID
      - value: 124
        label: INVALID
      - value: 125
        label: INVALID
      - value: 126
        label: INVALID
      - value: 127
        label: INVALID
      label: A/C Relay
    bind:
      source: config
      field: acRelayPin
  - type: enum-field
    id: acrelaypinmode
    props:
      label: A/C Relay Mode
      options:
      - value: 0
        label: default
      - value: 1
        label: default inverted
      - value: 2
        label: open collector
      - value: 3
        label: open collector inverted
    bind:
      source: config
      field: acRelayPinMode
  - type: scalar-field
    id: acdelay
    props:
      label: A/C compressor delay
    bind:
      source: config
      field: acDelay
  - type: scalar-field
    id: maxacrpm
    props:
      label: Max RPM
    bind:
      source: config
      field: maxAcRpm
  - type: scalar-field
    id: maxacclt
    props:
      label: Max CLT
    bind:
      source: config
      field: maxAcClt
  - type: scalar-field
    id: maxactps
    props:
      label: Max TPS
    bind:
      source: config
      field: maxAcTps
  - type: scalar-field
    id: acidleextraoffset
    props:
      label: A/C Idle adder
    bind:
      source: config
      field: acIdleExtraOffset
  - type: scalar-field
    id: acidlerpmtarget
    props:
      label: A/C Idle RPM
    bind:
      source: config
      field: acIdleRpmTarget
  - type: scalar-field
    id: aclowrpmlimit
    props:
      label: RPM low threshold
    bind:
      source: config
      field: acLowRpmLimit
  - type: scalar-field
    id: minacpressure
    props:
      label: Pressure Low disable
    bind:
      source: config
      field: minAcPressure
  - type: scalar-field
    id: maxacpressure
    props:
      label: Pressure High disable
    bind:
      source: config
      field: maxAcPressure
  - type: scalar-field
    id: acpressureenablehyst
    props:
      label: A/C Pressure Enable Hysteresis
    bind:
      source: config
      field: acPressureEnableHyst
- type: text
  props:
    variant: hint
    text: Панель «ac_controlIndicatorPanel» — нет определения в INI
