id: afterCrankingIACtaperDurationDialog.panel
description: Idle After Start (Crank-to-Run) Taper vs CLT
source:
  ini_dialog: afterCrankingIACtaperDurationDialog
  menu_path: Idle › Idle After Start (Crank-to-Run) Taper vs CLT
children:
- type: curve
  id: aftercrankingiactapercurve
  props:
    title: Idle valve Crank-to-Run Taper
    xLabel: Coolant
    yLabel: cyles
  bind:
    source: config
    params:
      xBins: afterCrankingIACtaperDurationBins
      yBins: afterCrankingIACtaperDuration
