id: afterCrankingIACtaperDurationDialog.panel
description: Idle After Start (Crank-to-Run) Taper vs CLT
source:
  ini_dialog: afterCrankingIACtaperDurationDialog
  menu_path: Idle › Idle After Start (Crank-to-Run) Taper vs CLT
children:
- type: curve
  id: aftercrankingiactapercurve
  props:
    xBins: afterCrankingIACtaperDurationBins
    xLabel: Coolant
    yBins: afterCrankingIACtaperDuration
    yLabel: cyles
    title: Idle valve Crank-to-Run Taper
