id: afterCrankingIACtaperDurationDialog.panel
description: Idle Valve Crank-to-Run Taper
source:
  ini_dialog: afterCrankingIACtaperDurationDialog
  menu_path: Idle › Idle Valve Crank-to-Run Taper
children:
- type: config-table
  id: aftercrankingiactapercurve
  props:
    xLabel: Coolant
    xBins: afterCrankingIACtaperDurationBins
    yBins: afterCrankingIACtaperDuration
    variant: curve
    title: Idle valve Crank-to-Run Taper
    yLabel: cyles
