id: analogInputSettings.panel
description: Analog Input Settings
source:
  ini_dialog: analogInputSettings
  menu_path: Sensors › Chassis sensors › Analog input settings
children:
- type: text
  props:
    variant: hint
    text: ECU reboot needed to apply these settings
- type: enum-field
  id: usefixedbarocorrfrommap
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: Grab baro value from MAP
  bind:
    source: config
    field: useFixedBaroCorrFromMap
