id: boostTargetDialog.panel
description: Boost control target
source:
  ini_dialog: boostTargetDialog
  menu_path: Advanced › Boost Control › Boost control target
children:
- type: config-table
  id: boostclosedtbl
  props:
    variant: table
    title: Boost control target / Closed Loop (kPa)
  bind:
    source: config
    params:
      xBins: boostRpmBins
      yBins: boostClosedLoopLoadBins
      zBins: boostTableClosedLoop
