id: boostOpenLoopGearAdderDialog.panel
description: Boost control open loop gear adder
source:
  ini_dialog: boostOpenLoopGearAdderDialog
  menu_path: Advanced › Boost control open loop gear adder
children:
- type: config-table
  id: boostopenloopgearaddercurve
  props:
    yBins: gearBasedOpenLoopBoostAdder
    yLabel: duty cycle
    variant: curve
    xLabel: Gear
    title: Boost Open Loop gear-based modifier
    xBins: gearCountArray
