id: boostPidDialog.panel
description: Boost control PID
source:
  ini_dialog: boostPidDialog
  menu_path: Advanced › Boost Control › Boost control PID
children:
- type: scalar-field
  id: minimumboostclosedloopmap
  props:
    label: Enable closed loop above
  bind:
    source: config
    field: minimumBoostClosedLoopMap
- type: scalar-field
  id: boostpid-pfactor
  props:
    label: P Gain
  bind:
    source: config
    field: boostPid_pFactor
- type: scalar-field
  id: boostpid-ifactor
  props:
    label: I Gain
  bind:
    source: config
    field: boostPid_iFactor
- type: scalar-field
  id: boostpid-dfactor
  props:
    label: D Gain
  bind:
    source: config
    field: boostPid_dFactor
- type: scalar-field
  id: boostpid-minvalue
  props:
    label: Min adjustment
  bind:
    source: config
    field: boostPid_minValue
- type: scalar-field
  id: boostpid-maxvalue
  props:
    label: Max adjustment
  bind:
    source: config
    field: boostPid_maxValue
