id: boostTargetDialog.panel
description: Boost control target
source:
  ini_dialog: boostTargetDialog
  menu_path: Advanced › Boost control target
children:
- type: config-table
  id: boostclosedtbl
  props:
    title: Boost control target / Closed Loop (kPa)
    variant: table
    yBins: boostClosedLoopLoadBins
    zBins: boostTableClosedLoop
    xBins: boostRpmBins
