id: boostOpenLoopGearAdderDialog.panel
description: Boost control open loop gear adder
source:
  ini_dialog: boostOpenLoopGearAdderDialog
  menu_path: Advanced › Boost Control › Boost control open loop gear adder
children:
- type: curve
  id: boostopenloopgearaddercurve
  props:
    yLabel: duty cycle
    xLabel: Gear
    title: Boost Open Loop gear-based modifier
  bind:
    source: config
    params:
      yBins: gearBasedOpenLoopBoostAdder
      xBins: gearCountArray
