id: canBusMain.panel
description: CAN Bus Communication
source:
  ini_dialog: canBusMain
  menu_path: CAN-bus › CAN Bus Settings
children:
- type: section
  props:
    title: CAN Bus
  children:
  - type: enum-field
    id: cannbctype
    props:
      label: CAN dash type
      options:
      - value: 0
        label: None
      - value: 1
        label: FIAT
      - value: 2
        label: VAG
      - value: 3
        label: MAZDA RX8
      - value: 4
        label: BMW E46
      - value: 5
        label: W202
      - value: 6
        label: BMW E90
      - value: 7
        label: Haltech
      - value: 8
        label: VAG MQB
      - value: 9
        label: Nissan VQ35
      - value: 10
        label: Genesis Coupe
      - value: 11
        label: Honda K
      - value: 12
        label: AiM
      - value: 13
        label: MS Simplified Broadcast
      - value: 14
        label: type 14
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
    bind:
      source: config
      field: canNbcType
  - type: enum-field
    id: imutype
    props:
      options:
      - value: 0
        label: None
      - value: 1
        label: VAG
      - value: 2
        label: MM5.10
      - value: 3
        label: type 3
      - value: 4
        label: type 4
      - value: 5
        label: INVALID
      - value: 6
        label: INVALID
      - value: 7
        label: INVALID
      - value: 8
        label: INVALID
      - value: 9
        label: INVALID
      - value: 10
        label: INVALID
      - value: 11
        label: INVALID
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      label: Inertia Measurement Unit
    bind:
      source: config
      field: imuType
  - type: enum-field
    id: canreadenabled
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: CAN read enabled
    bind:
      source: config
      field: canReadEnabled
  - type: enum-field
    id: canwriteenabled
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: CAN write enabled
    bind:
      source: config
      field: canWriteEnabled
  - type: enum-field
    id: enableverbosecantx
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Enable rusEFI CAN broadcast
    bind:
      source: config
      field: enableVerboseCanTx
  - type: enum-field
    id: canbroadcastusechanneltwo
    props:
      options:
      - value: 0
        label: first
      - value: 1
        label: second
      label: rusEFI CAN data bus
    bind:
      source: config
      field: canBroadcastUseChannelTwo
  - type: scalar-field
    id: verbosecanbaseaddress
    props:
      label: rusEFI CAN data base address
    bind:
      source: config
      field: verboseCanBaseAddress
  - type: enum-field
    id: rusefiverbose29b
    props:
      options:
      - value: 0
        label: 11 bit
      - value: 1
        label: 29 bit
      label: rusEFI CAN data address type
    bind:
      source: config
      field: rusefiVerbose29b
  - type: scalar-field
    id: cansleepperiodms
    props:
      label: rusEFI CAN data period
    bind:
      source: config
      field: canSleepPeriodMs
  - type: enum-field
    id: enableextendedcanbroadcast
    props:
      label: Enable board state broadcast
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: enableExtendedCanBroadcast
- type: section
  props:
    title: Primary CAN
  children:
  - type: enum-field
    id: verbosecan
    props:
      label: Verbose Can
      options:
      - value: 0
        label: Do not print
      - value: 1
        label: Print all
    bind:
      source: config
      field: verboseCan
  - type: enum-field
    id: canbaudrate
    props:
      label: Bitrate
      options:
      - value: 0
        label: 33.33kbps
      - value: 1
        label: 50kbps
      - value: 2
        label: 83.33kbps
      - value: 3
        label: 100kbps
      - value: 4
        label: 125kbps
      - value: 5
        label: 250kbps
      - value: 6
        label: 500kbps
      - value: 7
        label: 1Mbps
    bind:
      source: config
      field: canBaudRate
  - type: enum-field
    id: canopenblt
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Allow OpenBLT
    bind:
      source: config
      field: canOpenBLT
- type: section
  props:
    title: Secondary CAN
  children:
  - type: enum-field
    id: verbosecan2
    props:
      options:
      - value: 0
        label: Do not print
      - value: 1
        label: Print all
      label: Verbose Can2
    bind:
      source: config
      field: verboseCan2
  - type: enum-field
    id: can2baudrate
    props:
      options:
      - value: 0
        label: 33.33kbps
      - value: 1
        label: 50kbps
      - value: 2
        label: 83.33kbps
      - value: 3
        label: 100kbps
      - value: 4
        label: 125kbps
      - value: 5
        label: 250kbps
      - value: 6
        label: 500kbps
      - value: 7
        label: 1Mbps
      label: Bitrate
    bind:
      source: config
      field: can2BaudRate
  - type: enum-field
    id: can2openblt
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Allow OpenBLT
    bind:
      source: config
      field: can2OpenBLT
