id: cltCrankingCurveDialog.panel
description: Cranking Idle Valve Curve
source:
  ini_dialog: cltCrankingCurveDialog
  menu_path: Idle › Cranking Idle Valve Curve
children:
- type: scalar-field
  id: etbidlethrottlerange
  props:
    label: ETB idle maximum angle
  bind:
    source: config
    field: etbIdleThrottleRange
- type: curve
  id: cltcrankingcurve
  props:
    yBins: cltCrankingCorr
    yLabel: Percent
    xBins: cltCrankingCorrBins
    xLabel: Coolant
    title: Cranking Idle Valve Curve
