id: cltCrankingCurveDialog.panel
description: Cranking Air Amount vs CLT
source:
  ini_dialog: cltCrankingCurveDialog
  menu_path: Cranking › Cranking Air Amount vs CLT
children:
- type: scalar-field
  id: etbidlethrottlerange
  props:
    label: ETB idle maximum angle
  bind:
    source: config
    field: etbIdleThrottleRange
- type: curve
  id: cltcrankingcurve
  props:
    xLabel: Coolant
    title: Cranking Idle Valve Curve
    yLabel: Percent
    xBins: cltCrankingCorrBins
    yBins: cltCrankingCorr
