id: cltFuelCorrCurveDialog.panel
description: Warmup enrichment
source:
  ini_dialog: cltFuelCorrCurveDialog
  menu_path: Fuel › Target AFR adder tables › Warmup enrichment
children:
- type: scalar-field
  id: this-table-is-a-global-multiplier
  props:
    label: This table is a global multiplier
  bind:
    source: config
    field: This table is a global multiplier
- type: scalar-field
  id: 1-00-means-no-correction
  props:
    label: 1.00 means no correction
  bind:
    source: config
    field: 1.00 means no correction
- type: scalar-field
  id: 1-20-means-20--extra-fuel
  props:
    label: 1.20 means 20% extra fuel
  bind:
    source: config
    field: 1.20 means 20% extra fuel
- type: scalar-field
  id: 0-80--means-20--less-fuel
  props:
    label: 0.80% means 20% less fuel
  bind:
    source: config
    field: 0.80% means 20% less fuel
- type: curve
  id: cltfuelcorrcurve
  props:
    yBins: cltFuelCorr
    xLabel: Coolant
    xBins: cltFuelCorrBins
    yLabel: Multiplier
    title: Warmup fuel manual Multiplier
