id: connection.panel
description: Connection
source:
  ini_dialog: connection
  menu_path: Controller › Connection
children:
- type: scalar-field
  id: uartconsoleserialspeed
  props:
    label: uartConsoleSerialSpeed
  bind:
    source: config
    field: uartConsoleSerialSpeed
- type: enum-field
  id: enablekline
  props:
    options:
    - value: 0
      label: disabled
    - value: 1
      label: enabled
    label: enableKline
  bind:
    source: config
    field: enableKline
