id: crankingDialog.panel
description: Cranking Settings
source:
  ini_dialog: crankingDialog
  menu_path: Cranking › Cranking settings
children:
- type: scalar-field
  id: cranking-rpm
  props:
    label: Cranking RPM limit
  bind:
    source: config
    field: cranking_rpm
- type: section
  props:
    title: Fuel
  children:
  - type: enum-field
    id: crankinginjectionmode
    props:
      options:
      - value: 0
        label: Simultaneous
      - value: 1
        label: Sequential
      - value: 2
        label: Batch
      - value: 3
        label: Single Point
      label: Injection mode
    bind:
      source: config
      field: crankingInjectionMode
  - type: enum-field
    id: userunningmathforcranking
    props:
      label: Fuel Source For Cranking
      options:
      - value: 0
        label: Fixed
      - value: 1
        label: Fuel Map
    bind:
      source: config
      field: useRunningMathForCranking
- type: section
  props:
    title: Ignition
  children:
  - type: enum-field
    id: useseparateadvanceforcranking
    props:
      options:
      - value: 0
        label: Fixed (auto taper)
      - value: 1
        label: Table
      label: Timing Advance mode
    bind:
      source: config
      field: useSeparateAdvanceForCranking
  - type: scalar-field
    id: crankingtimingangle
    props:
      label: Fixed cranking advance
    bind:
      source: config
      field: crankingTimingAngle
  - type: scalar-field
    id: ignitiondwellforcrankingms
    props:
      label: Fixed Cranking Dwell
    bind:
      source: config
      field: ignitionDwellForCrankingMs
- type: section
  props:
    title: Advanced
  children:
  - type: enum-field
    id: iscylindercleanupenabled
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Enable flood clear
    bind:
      source: config
      field: isCylinderCleanupEnabled
  - type: enum-field
    id: isfasterenginespinupenabled
    props:
      label: Enable faster engine spin-up
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: isFasterEngineSpinUpEnabled
  - type: enum-field
    id: useadvancecorrectionsforcranking
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Use Advance Corrections for cranking
    bind:
      source: config
      field: useAdvanceCorrectionsForCranking
  - type: enum-field
    id: flexcranking
    props:
      label: Use Flex Fuel cranking table
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: flexCranking
