id: dwellSettings.panel
description: Dwell
source:
  ini_dialog: dwellSettings
  menu_path: Ignition › Dwell
children:
- type: curve
  id: dwellcorrection
  props:
    title: Dwell time base
    xLabel: RPM
    yBins: sparkDwellValues
    yLabel: Dwell
    xBins: sparkDwellRpmBins
- type: curve
  id: dwellvoltagecorrection
  props:
    xBins: dwellVoltageCorrVoltBins
    title: Dwell voltage correction
    yLabel: Multiplier
    yBins: dwellVoltageCorrValues
    xLabel: Battery Volts
