id: dwellSettings.panel
description: Dwell
source:
  ini_dialog: dwellSettings
  menu_path: Ignition › Dwell
children:
- type: curve
  id: dwellcorrection
  props:
    yBins: sparkDwellValues
    xLabel: RPM
    title: Dwell time base
    yLabel: Dwell
    xBins: sparkDwellRpmBins
- type: curve
  id: dwellvoltagecorrection
  props:
    yLabel: Multiplier
    title: Dwell voltage correction
    xLabel: Battery Volts
    xBins: dwellVoltageCorrVoltBins
    yBins: dwellVoltageCorrValues
