id: dwellSettings.panel
description: Dwell
source:
  ini_dialog: dwellSettings
  menu_path: Ignition › Dwell
children:
- type: config-table
  id: dwellcorrection
  props:
    xBins: sparkDwellRpmBins
    yBins: sparkDwellValues
    title: Dwell time base
    variant: curve
    xLabel: RPM
    yLabel: Dwell
- type: config-table
  id: dwellvoltagecorrection
  props:
    yLabel: Multiplier
    xLabel: Battery Volts
    yBins: dwellVoltageCorrValues
    xBins: dwellVoltageCorrVoltBins
    variant: curve
    title: Dwell voltage correction
