id: ecuPasswordPanel.panel
description: Tune pincode
source:
  ini_dialog: ecuPasswordPanel
  menu_path: Controller › Tune Lock
children:
- type: enum-field
  id: yesunderstandlocking
  props:
    label: I understand ECU Locking
    options:
    - value: 0
      label: no
    - value: 1
      label: yes
  bind:
    source: config
    field: yesUnderstandLocking
- type: text
  props:
    text: Use console for unlocking
    variant: hint
- type: scalar-field
  id: tunehidingkey
  props:
    label: Tune read/write pincode
  bind:
    source: config
    field: tuneHidingKey
