id: ecuStimulator.panel
description: ECU stimulator
source:
  ini_dialog: ecuStimulator
  menu_path: Controller › ECU stimulator
children:
- type: scalar-field
  id: triggersimulatorrpm
  props:
    label: Trigger Simulator
  bind:
    source: config
    field: triggerSimulatorRpm
- type: text
  props:
    text: 'Кнопка: Enable internal trigger simulation (cmd_enable_self_stim)'
    variant: hint
- type: text
  props:
    text: 'Кнопка: Disable trigger simulation (cmd_disable_self_stim)'
    variant: hint
- type: scalar-field
  id: logicanalyzerpins1
  props:
    label: Logic input channel 1
  bind:
    source: config
    field: logicAnalyzerPins1
- type: scalar-field
  id: logicanalyzerpins2
  props:
    label: Logic input channel 2
  bind:
    source: config
    field: logicAnalyzerPins2
- type: scalar-field
  id: logicanalyzerpins3
  props:
    label: Logic input channel 3
  bind:
    source: config
    field: logicAnalyzerPins3
- type: scalar-field
  id: logicanalyzerpins4
  props:
    label: Logic input channel 4
  bind:
    source: config
    field: logicAnalyzerPins4
- type: scalar-field
  id: enginechartsize
  props:
    label: Engine chart size
  bind:
    source: config
    field: engineChartSize
