id: egtInputs.panel
description: EGT inputs
source:
  ini_dialog: egtInputs
  menu_path: Sensors › Turbo sensors › EGT
children:
- type: section
  props:
    title: CAN EGT sensors
  children:
  - type: scalar-field
    id: can-support-egt1-to-egt6-inputs
    props:
      label: CAN support EGT1 to EGT6 inputs
    bind:
      source: config
      field: CAN support EGT1 to EGT6 inputs
  - type: scalar-field
    id: enableaemxseriesegt
    props:
      label: CAN EGT (AEM X series of RusEFI)
    bind:
      source: config
      field: enableAemXSeriesEgt
- type: section
  props:
    title: SPI EGT sensors
  children:
  - type: scalar-field
    id: if-both-can-and-spi-egt-sensors-are-used--please-leave-two-first-for-can
    props:
      label: If both CAN and SPI EGT sensors are used, please leave two first for CAN
    bind:
      source: config
      field: If both CAN and SPI EGT sensors are used, please leave two first for CAN
  - type: scalar-field
    id: max31855spidevice
    props:
      label: MAX31855/MAX31856 SPI
    bind:
      source: config
      field: max31855spiDevice
  - type: scalar-field
    id: max31855-cs1
    props:
      label: CS for EGT1
    bind:
      source: config
      field: max31855_cs1
  - type: scalar-field
    id: max31855-cs2
    props:
      label: CS for EGT2
    bind:
      source: config
      field: max31855_cs2
  - type: scalar-field
    id: max31855-cs3
    props:
      label: CS for EGT3
    bind:
      source: config
      field: max31855_cs3
  - type: scalar-field
    id: max31855-cs4
    props:
      label: CS for EGT4
    bind:
      source: config
      field: max31855_cs4
  - type: scalar-field
    id: max31855-cs5
    props:
      label: CS for EGT5
    bind:
      source: config
      field: max31855_cs5
  - type: scalar-field
    id: max31855-cs6
    props:
      label: CS for EGT6
    bind:
      source: config
      field: max31855_cs6
  - type: scalar-field
    id: max31855-cs7
    props:
      label: CS for EGT7
    bind:
      source: config
      field: max31855_cs7
  - type: scalar-field
    id: max31855-cs8
    props:
      label: CS for EGT8
    bind:
      source: config
      field: max31855_cs8
