id: egtInputsCan.panel
description: CAN EGT sensors
source:
  ini_dialog: egtInputsCan
  menu_path: CAN-bus › CAN EGT sensors
children:
- type: scalar-field
  id: can-support-egt1-to-egt6-inputs
  props:
    label: CAN support EGT1 to EGT6 inputs
  bind:
    source: config
    field: CAN support EGT1 to EGT6 inputs
- type: enum-field
  id: enableaemxseriesegt
  props:
    label: CAN EGT (AEM X series of RusEFI)
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: enableAemXSeriesEgt
