id: engineChars.panel
description: Vehicle Information
source:
  ini_dialog: engineChars
  menu_path: Setup › Vehicle Information
children:
- type: enum-field
  id: uimode
  props:
    options:
    - value: 0
      label: Full
    - value: 1
      label: INVALID
    - value: 2
      label: Tuning
    - value: 3
      label: INVALID
    label: Tuning View
  bind:
    source: config
    field: uiMode
- type: section
  props:
    title: Engine Configuration
  children:
  - type: scalar-field
    id: cylinderscount
    props:
      label: Number of cylinders
    bind:
      source: config
      field: cylindersCount
  - type: scalar-field
    id: displacement
    props:
      label: Displacement
    bind:
      source: config
      field: displacement
  - type: enum-field
    id: firingorder
    props:
      label: Firing order
      options:
      - value: 0
        label: One Cylinder
      - value: 1
        label: 1-3-4-2
      - value: 2
        label: 1-2-4-3
      - value: 3
        label: 1-3-2-4
      - value: 4
        label: 1-5-3-6-2-4
      - value: 5
        label: 1-8-4-3-6-5-7-2
      - value: 6
        label: 1-2-4-5-3
      - value: 7
        label: 1-4-2-5-3-6
      - value: 8
        label: 1-2
      - value: 9
        label: 1-2-3-4-5-6
      - value: 10
        label: 1-2-3
      - value: 11
        label: 1-8-7-2-6-5-4-3
      - value: 12
        label: 1-5-4-2-6-3-7-8 Mustang
      - value: 13
        label: 1-6-3-2-5-4
      - value: 14
        label: 1-10-9-4-3-6-5-8-7_2
      - value: 15
        label: 1-7-5-11-3-9-6-12-2-8-4-10
      - value: 16
        label: 1-7-4-10-2-8-6-12-3-9-5-11
      - value: 17
        label: 1-4-3-2
      - value: 18
        label: 1-12-5-8-3-10-6-7-2-11-4-9
      - value: 19
        label: 1-2-7-8-4-5-6-3
      - value: 20
        label: 1-3-7-2-6-5-4-8 HO
      - value: 21
        label: 1-2-3-4-5-6-7-8-9
      - value: 22
        label: INVALID
      - value: 23
        label: 1-2-3-4-5-6-7-8-9-10-11-12
      - value: 24
        label: 1-3-2
      - value: 25
        label: 1-2-3-4-5-6-7-8
      - value: 26
        label: 1-5-4-8-6-3-7-2
      - value: 27
        label: 1-4-3-6-2-5
      - value: 28
        label: 1-8-7-3-6-5-4-2
      - value: 29
        label: 1-6-2-4-3-5
      - value: 30
        label: 1-6-5-4-3-2
      - value: 31
        label: 1-4-5-2-3-6
      - value: 32
        label: 1-5-4-8-3-7-2-6 Voodoo
      - value: 33
        label: 1-6-5-10-2-7-3-8-4-9
      - value: 34
        label: 1-8-6-2-7-3-4-5 F136
      - value: 35
        label: fo35
      - value: 36
        label: fo36
      - value: 37
        label: fo37
      - value: 38
        label: INVALID
      - value: 39
        label: INVALID
      - value: 40
        label: INVALID
      - value: 41
        label: INVALID
      - value: 42
        label: INVALID
      - value: 43
        label: INVALID
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: INVALID
      - value: 54
        label: INVALID
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: INVALID
      - value: 58
        label: INVALID
      - value: 59
        label: INVALID
      - value: 60
        label: INVALID
      - value: 61
        label: INVALID
      - value: 62
        label: INVALID
      - value: 63
        label: INVALID
      - value: 64
        label: INVALID
      - value: 65
        label: INVALID
      - value: 66
        label: INVALID
      - value: 67
        label: INVALID
      - value: 68
        label: INVALID
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: INVALID
      - value: 78
        label: INVALID
      - value: 79
        label: INVALID
      - value: 80
        label: INVALID
      - value: 81
        label: INVALID
      - value: 82
        label: INVALID
      - value: 83
        label: INVALID
      - value: 84
        label: INVALID
      - value: 85
        label: INVALID
      - value: 86
        label: INVALID
      - value: 87
        label: INVALID
      - value: 88
        label: INVALID
      - value: 89
        label: INVALID
      - value: 90
        label: INVALID
      - value: 91
        label: INVALID
      - value: 92
        label: INVALID
      - value: 93
        label: INVALID
      - value: 94
        label: INVALID
      - value: 95
        label: INVALID
      - value: 96
        label: INVALID
      - value: 97
        label: INVALID
      - value: 98
        label: INVALID
      - value: 99
        label: INVALID
      - value: 100
        label: INVALID
      - value: 101
        label: INVALID
      - value: 102
        label: INVALID
      - value: 103
        label: INVALID
      - value: 104
        label: INVALID
      - value: 105
        label: INVALID
      - value: 106
        label: INVALID
      - value: 107
        label: INVALID
      - value: 108
        label: INVALID
      - value: 109
        label: INVALID
      - value: 110
        label: INVALID
      - value: 111
        label: INVALID
      - value: 112
        label: INVALID
      - value: 113
        label: INVALID
      - value: 114
        label: INVALID
      - value: 115
        label: INVALID
      - value: 116
        label: INVALID
      - value: 117
        label: INVALID
      - value: 118
        label: INVALID
      - value: 119
        label: INVALID
      - value: 120
        label: INVALID
      - value: 121
        label: INVALID
      - value: 122
        label: INVALID
      - value: 123
        label: INVALID
      - value: 124
        label: INVALID
      - value: 125
        label: INVALID
      - value: 126
        label: INVALID
      - value: 127
        label: INVALID
    bind:
      source: config
      field: firingOrder
- type: section
  props:
    title: Engine Metadata
  children:
  - type: text
    props:
      variant: hint
      text: These metadata are used by rusEFI Online
  - type: scalar-field
    id: enginemake
    props:
      label: Engine Make
    bind:
      source: config
      field: engineMake
  - type: scalar-field
    id: enginecode
    props:
      label: Manufacturer Engine Code
    bind:
      source: config
      field: engineCode
  - type: scalar-field
    id: vehiclename
    props:
      label: Vehicle Name
    bind:
      source: config
      field: vehicleName
  - type: scalar-field
    id: vinnumber
    props:
      label: VIN
    bind:
      source: config
      field: vinNumber
- type: section
  props:
    title: Fuel
  children:
  - type: text
    props:
      variant: hint
      text: https://rusefi.com/s/fuel
  - type: enum-field
    id: fuelalgorithm
    props:
      label: Fuel strategy
      options:
      - value: 0
        label: Speed Density
      - value: 1
        label: MAF Air Charge
      - value: 2
        label: Alpha-N
      - value: 3
        label: Lua
    bind:
      source: config
      field: fuelAlgorithm
