id: fan1PwmCurveDialog.panel
description: Fan 1 PWM Curve
source:
  ini_dialog: fan1PwmCurveDialog
  menu_path: Setup › Limits and protection › Fan 1 PWM Curve
children:
- type: curve
  id: fan1pwmcurve
  props:
    yBins: fan1PwmValues
    title: Fan 1 PWM vs Temperature
    yLabel: PWM %
    xBins: fan1TempBins
    xLabel: Coolant
