id: fan2PwmCurveDialog.panel
description: Fan 2 PWM Curve
source:
  ini_dialog: fan2PwmCurveDialog
  menu_path: Setup › Limits and protection › Fan 2 PWM Curve
children:
- type: curve
  id: fan2pwmcurve
  props:
    xLabel: Coolant
    title: Fan 2 PWM vs Temperature
    yLabel: PWM %
  bind:
    source: config
    params:
      xBins: fan2TempBins
      yBins: fan2PwmValues
