id: fuelLevelDialog.panel
description: Fuel Level Sensor
source:
  ini_dialog: fuelLevelDialog
  menu_path: Sensors › Fuel sensors › Fuel level sensor
children:
- type: section
  props:
    title: fuelLevelSettings
  children:
  - type: enum-field
    id: fuellevelsensor
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: Analog Volt 5
      - value: 2
        label: Analog Volt 6
      - value: 3
        label: Analog Volt 7
      - value: 4
        label: Analog Volt 8
      - value: 5
        label: Analog Volt 9
      - value: 6
        label: Analog Volt 10
      - value: 7
        label: Analog Volt 11
      - value: 8
        label: Battery Sense
      - value: 9
        label: Analog Temp 3
      - value: 10
        label: Analog Temp 4
      - value: 11
        label: Analog Volt 1
      - value: 12
        label: Analog Volt 2
      - value: 13
        label: Analog Volt 3
      - value: 14
        label: Analog Volt 4
      - value: 15
        label: Analog Temp 1
      - value: 16
        label: Analog Temp 2
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      label: Input channel
    bind:
      source: config
      field: fuelLevelSensor
  - type: scalar-field
    id: fuellevellowthresholdvoltage
    props:
      label: Low threshold
    bind:
      source: config
      field: fuelLevelLowThresholdVoltage
  - type: scalar-field
    id: fuellevelhighthresholdvoltage
    props:
      label: High threshold
    bind:
      source: config
      field: fuelLevelHighThresholdVoltage
  - type: scalar-field
    id: fuellevelaveragingalpha
    props:
      label: Filter Alpha
    bind:
      source: config
      field: fuelLevelAveragingAlpha
  - type: scalar-field
    id: fuellevelupdateperiodsec
    props:
      label: Update period
    bind:
      source: config
      field: fuelLevelUpdatePeriodSec
  - type: curve
    id: fuellevelcurve
    props:
      xBins: fuelLevelBins
      title: Fuel Level
      xLabel: Voltage
      yLabel: '%'
      yBins: fuelLevelValues
- type: section
  props:
    title: fuelLevelGauges
