id: fuelPressureSensor.panel
description: Fuel pressure
source:
  ini_dialog: fuelPressureSensor
  menu_path: Sensors › Fuel sensors › Fuel pressure
children:
- type: section
  props:
    title: Fuel Pressure Sensor
  children:
  - type: section
    props:
      title: Fuel Low Pressure Sensor
    children:
    - type: enum-field
      id: lowpressurefuel-hwchannel
      props:
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
        label: Analog input
      bind:
        source: config
        field: lowPressureFuel_hwChannel
    - type: enum-field
      id: fuelpressuresensormode
      props:
        options:
        - value: 0
          label: Absolute
        - value: 1
          label: Gauge
        - value: 2
          label: Differential
        - value: 3
          label: INVALID
        label: sensor type
      bind:
        source: config
        field: fuelPressureSensorMode
    - type: section
      props:
        title: Sensor scaling
      children:
      - type: scalar-field
        id: lowpressurefuel-v1
        props:
          label: low voltage
        bind:
          source: config
          field: lowPressureFuel_v1
      - type: scalar-field
        id: lowpressurefuel-value1
        props:
          label: low pressure
        bind:
          source: config
          field: lowPressureFuel_value1
      - type: scalar-field
        id: lowpressurefuel-v2
        props:
          label: high voltage
        bind:
          source: config
          field: lowPressureFuel_v2
      - type: scalar-field
        id: lowpressurefuel-value2
        props:
          label: high pressure
        bind:
          source: config
          field: lowPressureFuel_value2
  - type: section
    props:
      title: Fuel High Pressure Sensor
    children:
    - type: text
      props:
        text: "\"Sensor SENT type\"\t\t\t\t\t\tFuelHighPressureSentType"
        variant: hint
    - type: enum-field
      id: fuelhighpressuresentinput
      props:
        label: Sensor SENT input
        options:
        - value: 0
          label: None
        - value: 1
          label: SENT input 1
        - value: 2
          label: SENT input 2
        - value: 3
          label: SENT input 3
        - value: 4
          label: SENT input 4
        - value: 5
          label: SENT input 5
        - value: 6
          label: SENT input 6
        - value: 7
          label: SENT input 7
      bind:
        source: config
        field: FuelHighPressureSentInput
    - type: enum-field
      id: highpressurefuel-hwchannel
      props:
        label: Analog input
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
      bind:
        source: config
        field: highPressureFuel_hwChannel
    - type: section
      props:
        title: Sensor scaling
      children:
      - type: scalar-field
        id: highpressurefuel-v1
        props:
          label: low voltage
        bind:
          source: config
          field: highPressureFuel_v1
      - type: scalar-field
        id: highpressurefuel-value1
        props:
          label: low pressure
        bind:
          source: config
          field: highPressureFuel_value1
      - type: scalar-field
        id: highpressurefuel-v2
        props:
          label: high voltage
        bind:
          source: config
          field: highPressureFuel_v2
      - type: scalar-field
        id: highpressurefuel-value2
        props:
          label: high pressure
        bind:
          source: config
          field: highPressureFuel_value2
- type: section
  props:
    title: fuelPressureGauges
