id: gppwm1.panel
description: General Purpose PWM 1
source:
  ini_dialog: gppwm1
  menu_path: Advanced › Boost blend tables › General Purpose PWM 1
children:
- type: section
  props:
    title: gppwm1left
  children:
  - type: enum-field
    id: gppwm1-pin
    props:
      label: Output
      options:
      - value: 0
        label: NONE
      - value: 1
        label: INVALID
      - value: 2
        label: INVALID
      - value: 3
        label: INVALID
      - value: 4
        label: INVALID
      - value: 5
        label: INVALID
      - value: 6
        label: INVALID
      - value: 7
        label: INVALID
      - value: 8
        label: INVALID
      - value: 9
        label: INVALID
      - value: 10
        label: Highside 2
      - value: 11
        label: Highside 1
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: Lowside 8
      - value: 23
        label: Lowside 9
      - value: 24
        label: Lowside 10
      - value: 25
        label: Lowside 11
      - value: 26
        label: Lowside 12
      - value: 27
        label: Lowside 13
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      - value: 32
        label: INVALID
      - value: 33
        label: INVALID
      - value: 34
        label: INVALID
      - value: 35
        label: INVALID
      - value: 36
        label: INVALID
      - value: 37
        label: INVALID
      - value: 38
        label: INVALID
      - value: 39
        label: INVALID
      - value: 40
        label: INVALID
      - value: 41
        label: Ign 5
      - value: 42
        label: Ign 4
      - value: 43
        label: Ign 3
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: Ign 2
      - value: 54
        label: Ign 1
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: Lowside 1
      - value: 58
        label: STM32 PD8
      - value: 59
        label: STM32 PD9
      - value: 60
        label: STM32 PD10
      - value: 61
        label: STM32 PD11
      - value: 62
        label: STM32 PD12
      - value: 63
        label: STM32 PD13
      - value: 64
        label: Highside 4
      - value: 65
        label: Highside 3
      - value: 66
        label: Lowside 14 or starter
      - value: 67
        label: Lowside 15
      - value: 68
        label: Lowside 16
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: INVALID
      - value: 78
        label: INVALID
      - value: 79
        label: INVALID
      - value: 80
        label: INVALID
      - value: 81
        label: INVALID
      - value: 82
        label: INVALID
      - value: 83
        label: INVALID
      - value: 84
        label: INVALID
      - value: 85
        label: INVALID
      - value: 86
        label: INVALID
      - value: 87
        label: INVALID
      - value: 88
        label: INVALID
      - value: 89
        label: INVALID
      - value: 90
        label: INVALID
      - value: 91
        label: INVALID
      - value: 92
        label: INVALID
      - value: 93
        label: INVALID
      - value: 94
        label: INVALID
      - value: 95
        label: INVALID
      - value: 96
        label: INVALID
      - value: 97
        label: INVALID
      - value: 98
        label: INVALID
      - value: 99
        label: INVALID
      - value: 100
        label: Ign 12
      - value: 101
        label: Ign 11
      - value: 102
        label: Ign 10
      - value: 103
        label: Ign 9
      - value: 104
        label: Ign 8
      - value: 105
        label: Ign 7
      - value: 106
        label: Ign 6
      - value: 107
        label: Lowside 2
      - value: 108
        label: Lowside 3
      - value: 109
        label: Lowside 4
      - value: 110
        label: Lowside 5
      - value: 111
        label: Lowside 6
      - value: 112
        label: Lowside 7
    bind:
      source: config
      field: gppwm1_pin
  - type: scalar-field
    id: set-frequency-to-0hz-for-on-off-mode
    props:
      label: Set frequency to 0hz for on-off mode
    bind:
      source: config
      field: Set frequency to 0hz for on-off mode
  - type: scalar-field
    id: gppwm1-pwmfrequency
    props:
      label: Frequency
    bind:
      source: config
      field: gppwm1_pwmFrequency
  - type: scalar-field
    id: gppwm1-onaboveduty
    props:
      label: On above duty
    bind:
      source: config
      field: gppwm1_onAboveDuty
  - type: scalar-field
    id: gppwm1-offbelowduty
    props:
      label: Off below duty
    bind:
      source: config
      field: gppwm1_offBelowDuty
  - type: scalar-field
    id: gppwm1-dutyiferror
    props:
      label: Duty if error
    bind:
      source: config
      field: gppwm1_dutyIfError
  - type: enum-field
    id: gppwm1-rpmaxis
    props:
      options:
      - value: 0
        label: Zero
      - value: 1
        label: TPS
      - value: 2
        label: MAP
      - value: 3
        label: CLT
      - value: 4
        label: IAT
      - value: 5
        label: Fuel Load
      - value: 6
        label: Ignition Load
      - value: 7
        label: Aux Temp 1
      - value: 8
        label: Aux Temp 2
      - value: 9
        label: Accel Pedal
      - value: 10
        label: Battery Voltage
      - value: 11
        label: VVT 1 In Actual
      - value: 12
        label: VVT 1 Ex Actual
      - value: 13
        label: VVT 2 In Actual
      - value: 14
        label: VVT 2 Ex Actual
      - value: 15
        label: Ethanol (Flex) %
      - value: 16
        label: Aux Linear 1
      - value: 17
        label: Aux Linear 2
      - value: 18
        label: GPPWM Output 1
      - value: 19
        label: GPPWM Output 2
      - value: 20
        label: GPPWM Output 3
      - value: 21
        label: GPPWM Output 4
      - value: 22
        label: Lua Gauge 1
      - value: 23
        label: Lua Gauge 2
      - value: 24
        label: RPM
      - value: 25
        label: Gear (detected)
      - value: 26
        label: Baro pressure
      - value: 27
        label: EGT 1
      - value: 28
        label: EGT 2
      - value: 29
        label: Aux Linear 3
      - value: 30
        label: Aux Linear 4
      - value: 31
        label: Vehicle speed
      - value: 32
        label: Oil pressure
      - value: 33
        label: Oil temp
      - value: 34
        label: Fuel Pressure
      label: X Axis
    bind:
      source: config
      field: gppwm1_rpmAxis
  - type: enum-field
    id: gppwm1-loadaxis
    props:
      label: Y Axis
      options:
      - value: 0
        label: Zero
      - value: 1
        label: TPS
      - value: 2
        label: MAP
      - value: 3
        label: CLT
      - value: 4
        label: IAT
      - value: 5
        label: Fuel Load
      - value: 6
        label: Ignition Load
      - value: 7
        label: Aux Temp 1
      - value: 8
        label: Aux Temp 2
      - value: 9
        label: Accel Pedal
      - value: 10
        label: Battery Voltage
      - value: 11
        label: VVT 1 In Actual
      - value: 12
        label: VVT 1 Ex Actual
      - value: 13
        label: VVT 2 In Actual
      - value: 14
        label: VVT 2 Ex Actual
      - value: 15
        label: Ethanol (Flex) %
      - value: 16
        label: Aux Linear 1
      - value: 17
        label: Aux Linear 2
      - value: 18
        label: GPPWM Output 1
      - value: 19
        label: GPPWM Output 2
      - value: 20
        label: GPPWM Output 3
      - value: 21
        label: GPPWM Output 4
      - value: 22
        label: Lua Gauge 1
      - value: 23
        label: Lua Gauge 2
      - value: 24
        label: RPM
      - value: 25
        label: Gear (detected)
      - value: 26
        label: Baro pressure
      - value: 27
        label: EGT 1
      - value: 28
        label: EGT 2
      - value: 29
        label: Aux Linear 3
      - value: 30
        label: Aux Linear 4
      - value: 31
        label: Vehicle speed
      - value: 32
        label: Oil pressure
      - value: 33
        label: Oil temp
      - value: 34
        label: Fuel Pressure
    bind:
      source: config
      field: gppwm1_loadAxis
  - type: scalar-field
    id: gppwmnote1
    props:
      label: Note
    bind:
      source: config
      field: gpPwmNote1
- type: config-table
  id: gppwm1tbl
  props:
    yBins: gppwm1_loadBins
    zBins: gppwm1_table
    variant: table
    title: GP#1
    yLabel: gppwm1_rpmAxis)}
    xBins: gppwm1_rpmBins
