id: highOilPressureProtection.panel
description: High oil pressure protection
source:
  ini_dialog: highOilPressureProtection
  menu_path: Setup › Limits and protection › High oil pressure protection
children:
- type: scalar-field
  id: maxoilpressuretimeout
  props:
    label: High oil pressure protection timeout
  bind:
    source: config
    field: maxOilPressureTimeout
- type: curve
  id: maximumoilpressure
  props:
    title: Maximum oil pressure
    yLabel: max pressure
    xLabel: RPM
  bind:
    source: config
    params:
      yBins: maximumOilPressureValues
      xBins: maximumOilPressureBins
