id: hpfpCamDialog.panel
description: HPFP Cam Configuration
source:
  ini_dialog: hpfpCamDialog
  menu_path: Controller › HPFP Cam Configuration
children:
- type: scalar-field
  id: hpfpcamlobes
  props:
    label: Number of lobes
  bind:
    source: config
    field: hpfpCamLobes
- type: enum-field
  id: hpfpcam
  props:
    label: If using VVT, which cam the pump is driven from
    options:
    - value: 0
      label: NONE
    - value: 1
      label: Intake 1
    - value: 2
      label: Exhaust 1
    - value: 3
      label: Intake 2
    - value: 4
      label: Exhaust 2
    - value: 5
      label: INVALID
    - value: 6
      label: INVALID
    - value: 7
      label: INVALID
  bind:
    source: config
    field: hpfpCam
- type: scalar-field
  id: hpfppeakpos
  props:
    label: Angle of first lobe peak
  bind:
    source: config
    field: hpfpPeakPos
- type: curve
  id: hpfplobeprofilecurve
  props:
    xBins: hpfpLobeProfileQuantityBins
    yBins: hpfpLobeProfileAngle
    xLabel: '% pump volume'
    title: HPFP Lobe Profile
    yLabel: angle
