id: ignitionCylExtra.panel
description: Cylinder offsets
source:
  ini_dialog: ignitionCylExtra
  menu_path: Advanced › Torque Control › Cylinder offsets
children:
- type: scalar-field
  id: offset-angle-for-each-cylinder-if-you-have-an-odd-fire
  props:
    label: Offset angle for each cylinder if you have an odd fire
  bind:
    source: config
    field: Offset angle for each cylinder if you have an odd fire
- type: scalar-field
  id: engine--like-a-v-twin-or-some-v6-v10-engines
  props:
    label: engine, like a v-twin or some V6/V10 engines
  bind:
    source: config
    field: engine, like a v-twin or some V6/V10 engines
- type: text
  props:
    variant: hint
    text: Positive numbers retard, negative numbers advance
- type: scalar-field
  id: timing-offset-cylinder1
  props:
    label: Offset cyl 1
  bind:
    source: config
    field: timing_offset_cylinder1
- type: scalar-field
  id: timing-offset-cylinder2
  props:
    label: Offset cyl 2
  bind:
    source: config
    field: timing_offset_cylinder2
- type: scalar-field
  id: timing-offset-cylinder3
  props:
    label: Offset cyl 3
  bind:
    source: config
    field: timing_offset_cylinder3
- type: scalar-field
  id: timing-offset-cylinder4
  props:
    label: Offset cyl 4
  bind:
    source: config
    field: timing_offset_cylinder4
- type: scalar-field
  id: timing-offset-cylinder5
  props:
    label: Offset cyl 5
  bind:
    source: config
    field: timing_offset_cylinder5
- type: scalar-field
  id: timing-offset-cylinder6
  props:
    label: Offset cyl 6
  bind:
    source: config
    field: timing_offset_cylinder6
- type: scalar-field
  id: timing-offset-cylinder7
  props:
    label: Offset cyl 7
  bind:
    source: config
    field: timing_offset_cylinder7
- type: scalar-field
  id: timing-offset-cylinder8
  props:
    label: Offset cyl 8
  bind:
    source: config
    field: timing_offset_cylinder8
- type: scalar-field
  id: timing-offset-cylinder9
  props:
    label: Offset cyl 9
  bind:
    source: config
    field: timing_offset_cylinder9
- type: scalar-field
  id: timing-offset-cylinder10
  props:
    label: Offset cyl 10
  bind:
    source: config
    field: timing_offset_cylinder10
- type: scalar-field
  id: timing-offset-cylinder11
  props:
    label: Offset cyl 11
  bind:
    source: config
    field: timing_offset_cylinder11
- type: scalar-field
  id: timing-offset-cylinder12
  props:
    label: Offset cyl 12
  bind:
    source: config
    field: timing_offset_cylinder12
