id: injTest.panel
description: Injector test
source:
  ini_dialog: injTest
  menu_path: Controller › Injector test
children:
- type: section
  props:
    title: Output test modes
  children:
  - type: scalar-field
    id: benchtestcount
    props:
      label: Iterations
    bind:
      source: config
      field: benchTestCount
  - type: scalar-field
    id: benchtestontime
    props:
      label: On Time
    bind:
      source: config
      field: benchTestOnTime
  - type: scalar-field
    id: benchtestofftime
    props:
      label: Off Time
    bind:
      source: config
      field: benchTestOffTime
- type: section
  props:
    title: Reference gauges
