id: lambdaProtection.panel
description: Lambda Protection
source:
  ini_dialog: lambdaProtection
  menu_path: Setup › Limits and protection › Lambda protection
children:
- type: section
  props:
    title: lambdaProtectionLeft
  children:
  - type: enum-field
    id: lambdaprotectionenable
    props:
      label: Enable lambda protection
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: lambdaProtectionEnable
  - type: scalar-field
    id: lambdaprotectionminload
    props:
      label: Check above load
    bind:
      source: config
      field: lambdaProtectionMinLoad
  - type: scalar-field
    id: lambdaprotectionmintps
    props:
      label: and above TPS
    bind:
      source: config
      field: lambdaProtectionMinTps
  - type: scalar-field
    id: lambdaprotectionminrpm
    props:
      label: and above RPM
    bind:
      source: config
      field: lambdaProtectionMinRpm
  - type: text
    props:
      text: and after delay
      variant: hint
  - type: scalar-field
    id: then-cut-fuel-until
    props:
      label: 'Then cut fuel until:'
    bind:
      source: config
      field: 'Then cut fuel until:'
  - type: scalar-field
    id: lambdaprotectionrestoreload
    props:
      label: Load less than
    bind:
      source: config
      field: lambdaProtectionRestoreLoad
  - type: scalar-field
    id: lambdaprotectionrestoretps
    props:
      label: and TPS less than
    bind:
      source: config
      field: lambdaProtectionRestoreTps
  - type: scalar-field
    id: lambdaprotectionrestorerpm
    props:
      label: and RPM less than
    bind:
      source: config
      field: lambdaProtectionRestoreRpm
- type: section
  props:
    title: Lambda Difference Table
  children:
  - type: config-table
    id: lambdamaxdeviationtabletbl
    props:
      variant: table
      xLabel: RPM
      zBins: lambdaMaxDeviationTable
      title: Maximum Lambda Deviation
      yBins: lambdaMaxDeviationLoadBins
      xBins: lambdaMaxDeviationRpmBins
