id: lambdaTableDialog.panel
description: Target lambda
source:
  ini_dialog: lambdaTableDialog
  menu_path: Fuel › VE blend tables › Target lambda
children:
- type: section
  props:
    title: Load override
  children:
  - type: enum-field
    id: afroverridemode
    props:
      label: Override Lambda table load axis
      options:
      - value: 0
        label: None
      - value: 1
        label: MAP
      - value: 2
        label: TPS
      - value: 3
        label: Acc Pedal
      - value: 4
        label: Cyl Filling %
      - value: 5
        label: INVALID
      - value: 6
        label: INVALID
      - value: 7
        label: INVALID
    bind:
      source: config
      field: afrOverrideMode
- type: config-table
  id: lambdatabletbl
  props:
    variant: table
    xLabel: RPM
    xBins: lambdaRpmBins
    yBins: lambdaLoadBins
    title: Target Lambda Table
    zBins: lambdaTable
