id: lowOilPressureProtection.panel
description: Low oil pressure protection
source:
  ini_dialog: lowOilPressureProtection
  menu_path: Setup › Limits and protection › Low oil pressure protection
children:
- type: scalar-field
  id: minoilpressureafterstart
  props:
    label: Minimum oil pressure after start
  bind:
    source: config
    field: minOilPressureAfterStart
- type: enum-field
  id: enableoilpressureprotect
  props:
    label: Enable low oil pressure protection
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: enableOilPressureProtect
- type: scalar-field
  id: minimumoilpressuretimeout
  props:
    label: Low oil pressure protection timeout
  bind:
    source: config
    field: minimumOilPressureTimeout
- type: config-table
  id: minimumoilpressure
  props:
    xBins: minimumOilPressureBins
    yBins: minimumOilPressureValues
    xLabel: RPM
    title: Minimum oil pressure
    yLabel: min pressure
    variant: curve
