id: mafSettings.panel
description: MAF sensor
source:
  ini_dialog: mafSettings
  menu_path: Sensors › Chassis sensors › MAF sensor
children:
- type: text
  props:
    variant: hint
    text: <html><a href=https://github.com/rusefi/rusefi/wiki/MAF>https://github.com/rusefi/rusefi/wiki/MAF</a></html>
- type: enum-field
  id: mafadcchannel
  props:
    options:
    - value: 0
      label: NONE
    - value: 1
      label: Analog Volt 5
    - value: 2
      label: Analog Volt 6
    - value: 3
      label: Analog Volt 7
    - value: 4
      label: Analog Volt 8
    - value: 5
      label: Analog Volt 9
    - value: 6
      label: Analog Volt 10
    - value: 7
      label: Analog Volt 11
    - value: 8
      label: Battery Sense
    - value: 9
      label: Analog Temp 3
    - value: 10
      label: Analog Temp 4
    - value: 11
      label: Analog Volt 1
    - value: 12
      label: Analog Volt 2
    - value: 13
      label: Analog Volt 3
    - value: 14
      label: Analog Volt 4
    - value: 15
      label: Analog Temp 1
    - value: 16
      label: Analog Temp 2
    label: MAF ADC input
  bind:
    source: config
    field: mafAdcChannel
- type: enum-field
  id: maf2adcchannel
  props:
    options:
    - value: 0
      label: NONE
    - value: 1
      label: Analog Volt 5
    - value: 2
      label: Analog Volt 6
    - value: 3
      label: Analog Volt 7
    - value: 4
      label: Analog Volt 8
    - value: 5
      label: Analog Volt 9
    - value: 6
      label: Analog Volt 10
    - value: 7
      label: Analog Volt 11
    - value: 8
      label: Battery Sense
    - value: 9
      label: Analog Temp 3
    - value: 10
      label: Analog Temp 4
    - value: 11
      label: Analog Volt 1
    - value: 12
      label: Analog Volt 2
    - value: 13
      label: Analog Volt 3
    - value: 14
      label: Analog Volt 4
    - value: 15
      label: Analog Temp 1
    - value: 16
      label: Analog Temp 2
    label: MAF 2 ADC input
  bind:
    source: config
    field: maf2AdcChannel
- type: scalar-field
  id: maffilterparameter
  props:
    label: MAF filter parameter
  bind:
    source: config
    field: mafFilterParameter
