id: mapCurves.panel
description: MAP sampling
source:
  ini_dialog: mapCurves
  menu_path: Sensors › Chassis sensors › MAP sampling
children:
- type: enum-field
  id: ismapaveragingenabled
  props:
    label: Window averaging
    options:
    - value: 0
      label: disabled
    - value: 1
      label: enabled
  bind:
    source: config
    field: isMapAveragingEnabled
- type: scalar-field
  id: mapexpaveragealpha
  props:
    label: mapExpAverageAlpha
  bind:
    source: config
    field: mapExpAverageAlpha
- type: curve
  id: map-samplinganglecurve
  props:
    title: MAP Sampling Start Angle
    yBins: map_samplingAngle
    yLabel: Angle
    xBins: map_samplingAngleBins
    xLabel: RPM
- type: curve
  id: map-samplingwindowcurve
  props:
    yBins: map_samplingWindow
    title: MAP Sampling Duration
    xBins: map_samplingWindowBins
    xLabel: RPM
    yLabel: Window
