id: mapCurves.panel
description: MAP sampling
source:
  ini_dialog: mapCurves
  menu_path: Sensors › Chassis sensors › MAP sampling
children:
- type: enum-field
  id: ismapaveragingenabled
  props:
    label: Window averaging
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: isMapAveragingEnabled
- type: scalar-field
  id: mapexpaveragealpha
  props:
    label: mapExpAverageAlpha
  bind:
    source: config
    field: mapExpAverageAlpha
- type: config-table
  id: map-samplinganglecurve
  props:
    xLabel: RPM
    yBins: map_samplingAngle
    xBins: map_samplingAngleBins
    yLabel: Angle
    variant: curve
    title: MAP Sampling Start Angle
- type: config-table
  id: map-samplingwindowcurve
  props:
    xLabel: RPM
    xBins: map_samplingWindowBins
    variant: curve
    yBins: map_samplingWindow
    title: MAP Sampling Duration
    yLabel: Window
