id: monitoringSettings.panel
description: rusEFI Console Settings
source:
  ini_dialog: monitoringSettings
  menu_path: Controller › rusEFI console
children:
- type: scalar-field
  id: enginesnifferrpmthreshold
  props:
    label: Engine Sniffer Threshold
  bind:
    source: config
    field: engineSnifferRpmThreshold
