id: msIoBox.panel
description: CAN MS IO-Box Settings
source:
  ini_dialog: msIoBox
  menu_path: CAN-bus › CAN MS IO-Box Settings
children:
- type: section
  props:
    title: MS IO box 1
  children:
  - type: enum-field
    id: msiobox0-id
    props:
      options:
      - value: 0
        label: Off
      - value: 1
        label: ID1 (0x200)
      - value: 2
        label: ID2 (0x220)
      - value: 3
        label: ID3 (0x240)
      label: Base CAN identifier
    bind:
      source: config
      field: msIoBox0_id
  - type: enum-field
    id: msiobox0-vss
    props:
      label: VSS settings
      options:
      - value: 0
        label: Off
      - value: 1
        label: VR speed in (1, 2)
      - value: 2
        label: Hall speed in (3, 4)
      - value: 3
        label: All (1, 2, 3, 4)
    bind:
      source: config
      field: msIoBox0_vss
