id: multisparkSettings.panel
description: Multispark
source:
  ini_dialog: multisparkSettings
  menu_path: Ignition › Cylinder ign trims › Multispark
children:
- type: text
  props:
    variant: hint
    text: WARNING! These settings have the potential to overheat ignition components
- type: text
  props:
    text: and cause other nasty misbehavior.  Use with care, at your own risk!
    variant: hint
- type: text
  props:
    variant: hint
    text: Not recommended for use on distributor or wasted spark ignition systems.
- type: enum-field
  id: multisparkenable
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: Enable multiple sparks
  bind:
    source: config
    field: multisparkEnable
- type: section
  props:
    title: Configuration
  children:
  - type: scalar-field
    id: multisparkmaxrpm
    props:
      label: Maximum engine speed
    bind:
      source: config
      field: multisparkMaxRpm
  - type: text
    props:
      variant: hint
      text: "\"Fire sparks for this angle duration\"\tmultisparkMaxSparkingAngle"
  - type: text
    props:
      variant: hint
      text: "\"Maximum extra spark count\"\t\t\t\tmultisparkMaxExtraSparkCount"
- type: section
  props:
    title: Delay & Dwell
  children:
  - type: scalar-field
    id: multisparksparkduration
    props:
      label: Spark duration
    bind:
      source: config
      field: multisparkSparkDuration
  - type: scalar-field
    id: multisparkdwell
    props:
      label: Subsequent spark dwell
    bind:
      source: config
      field: multisparkDwell
