id: oilTempSensor.panel
description: Oil Temp Sensor Settings
source:
  ini_dialog: oilTempSensor
  menu_path: Sensors › Oil sensors › Oil temp sensor
children:
- type: enum-field
  id: oiltempsensor-adcchannel
  props:
    options:
    - value: 0
      label: NONE
    - value: 1
      label: Analog Volt 5
    - value: 2
      label: Analog Volt 6
    - value: 3
      label: Analog Volt 7
    - value: 4
      label: Analog Volt 8
    - value: 5
      label: Analog Volt 9
    - value: 6
      label: Analog Volt 10
    - value: 7
      label: Analog Volt 11
    - value: 8
      label: Battery Sense
    - value: 9
      label: Analog Temp 3
    - value: 10
      label: Analog Temp 4
    - value: 11
      label: Analog Volt 1
    - value: 12
      label: Analog Volt 2
    - value: 13
      label: Analog Volt 3
    - value: 14
      label: Analog Volt 4
    - value: 15
      label: Analog Temp 1
    - value: 16
      label: Analog Temp 2
    label: Input channel
  bind:
    source: config
    field: oilTempSensor_adcChannel
- type: scalar-field
  id: oiltempsensor-bias-resistor
  props:
    label: Pullup resistor
  bind:
    source: config
    field: oilTempSensor_bias_resistor
- type: scalar-field
  id: oiltempsensor-tempc-1
  props:
    label: Lowest temperature
  bind:
    source: config
    field: oilTempSensor_tempC_1
- type: scalar-field
  id: oiltempsensor-resistance-1
  props:
    label: Resistance @ LT
  bind:
    source: config
    field: oilTempSensor_resistance_1
- type: scalar-field
  id: oiltempsensor-tempc-2
  props:
    label: Middle temperature
  bind:
    source: config
    field: oilTempSensor_tempC_2
- type: scalar-field
  id: oiltempsensor-resistance-2
  props:
    label: Resistance @ MT
  bind:
    source: config
    field: oilTempSensor_resistance_2
- type: scalar-field
  id: oiltempsensor-tempc-3
  props:
    label: Highest temperature
  bind:
    source: config
    field: oilTempSensor_tempC_3
- type: scalar-field
  id: oiltempsensor-resistance-3
  props:
    label: Resistance @ HT
  bind:
    source: config
    field: oilTempSensor_resistance_3
