id: outputsDialog.panel
description: Outputs
source:
  ini_dialog: outputsDialog
  menu_path: Setup › Limits and protection › Outputs
children:
- type: section
  props:
    title: outputsDialogLeft
- type: section
  props:
    title: outputsDialogRight
