id: parkingLot.panel
description: Experimental/Broken
source:
  ini_dialog: parkingLot
  menu_path: Controller › Experimental 1
children:
- type: enum-field
  id: uimode
  props:
    options:
    - value: 0
      label: Full
    - value: 1
      label: INVALID
    - value: 2
      label: Tuning
    - value: 3
      label: INVALID
    label: uiMode
  bind:
    source: config
    field: uiMode
- type: enum-field
  id: can1listenmode
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: can1ListenMode
  bind:
    source: config
    field: can1ListenMode
- type: enum-field
  id: can2listenmode
  props:
    label: can2ListenMode
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: can2ListenMode
- type: enum-field
  id: rethrowhardfault
  props:
    label: rethrowHardFault
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: rethrowHardFault
- type: enum-field
  id: cangpiotype
  props:
    label: canGpioType
    options:
    - value: 0
      label: None
    - value: 1
      label: DRT protocol
    - value: 2
      label: MS protocol
    - value: 3
      label: INVALID
  bind:
    source: config
    field: canGpioType
- type: enum-field
  id: yesunderstandlocking
  props:
    options:
    - value: 0
      label: no
    - value: 1
      label: yes
    label: I understand ECU Locking
  bind:
    source: config
    field: yesUnderstandLocking
- type: text
  props:
    variant: hint
    text: Use console for unlocking
- type: scalar-field
  id: tunehidingkey
  props:
    label: Tune read/write password
  bind:
    source: config
    field: tuneHidingKey
- type: enum-field
  id: verbosequad
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: verboseQuad
  bind:
    source: config
    field: verboseQuad
- type: text
  props:
    variant: hint
    text: System hacks
- type: enum-field
  id: vvtbooleanforveryspecialcases
  props:
    label: vvtBooleanForVerySpecialCases
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: vvtBooleanForVerySpecialCases
- type: enum-field
  id: watchoutforlineartime
  props:
    label: watchOutForLinearTime
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: watchOutForLinearTime
- type: enum-field
  id: verboseisotp
  props:
    label: TS over CAN debug
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: verboseIsoTp
- type: enum-field
  id: consumeobdsensors
  props:
    label: consumeObdSensors
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: consumeObdSensors
- type: enum-field
  id: allowidenticalpps
  props:
    label: BRZ/FRS/GT86 pedal
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: allowIdenticalPps
- type: enum-field
  id: artificialtestmisfire
  props:
    options:
    - value: 0
      label: No thank you
    - value: 1
      label: Danger Mode
    label: Artificial Misfire
  bind:
    source: config
    field: artificialTestMisfire
- type: enum-field
  id: alwaysinstantrpm
  props:
    label: Always use instant RPM
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: alwaysInstantRpm
- type: enum-field
  id: modeledflowidle
  props:
    label: Modeled flow idle
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: modeledFlowIdle
- type: scalar-field
  id: idlemaximumairmass
  props:
    label: Max idle flow
  bind:
    source: config
    field: idleMaximumAirmass
- type: scalar-field
  id: vinnumber
  props:
    label: vinNumber
  bind:
    source: config
    field: vinNumber
- type: scalar-field
  id: turbochargerfilter
  props:
    label: turbochargerFilter
  bind:
    source: config
    field: turbochargerFilter
- type: scalar-field
  id: auxfrequencyfilter
  props:
    label: auxFrequencyFilter
  bind:
    source: config
    field: auxFrequencyFilter
- type: enum-field
  id: usebiquadonauxspeedsensors
  props:
    label: useBiQuadOnAuxSpeedSensors
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
  bind:
    source: config
    field: useBiQuadOnAuxSpeedSensors
- type: enum-field
  id: kickstartcranking
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: TODO KS mode 4569
  bind:
    source: config
    field: kickStartCranking
