id: pedalSensor.panel
description: Accelerator pedal
source:
  ini_dialog: pedalSensor
  menu_path: Sensors › Chassis sensors › Accelerator pedal
children:
- type: section
  props:
    title: Accelerator pedal
  children:
  - type: enum-field
    id: throttlepedalpositionadcchannel
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: Analog Volt 5
      - value: 2
        label: Analog Volt 6
      - value: 3
        label: Analog Volt 7
      - value: 4
        label: Analog Volt 8
      - value: 5
        label: Analog Volt 9
      - value: 6
        label: Analog Volt 10
      - value: 7
        label: Analog Volt 11
      - value: 8
        label: Battery Sense
      - value: 9
        label: Analog Temp 3
      - value: 10
        label: Analog Temp 4
      - value: 11
        label: Analog Volt 1
      - value: 12
        label: Analog Volt 2
      - value: 13
        label: Analog Volt 3
      - value: 14
        label: Analog Volt 4
      - value: 15
        label: Analog Temp 1
      - value: 16
        label: Analog Temp 2
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      label: Accelerator position primary sensor
    bind:
      source: config
      field: throttlePedalPositionAdcChannel
  - type: scalar-field
    id: throttlepedalupvoltage
    props:
      label: Up (idle) voltage
    bind:
      source: config
      field: throttlePedalUpVoltage
  - type: scalar-field
    id: throttlepedalwotvoltage
    props:
      label: Down (WOT) voltage
    bind:
      source: config
      field: throttlePedalWOTVoltage
  - type: enum-field
    id: throttlepedalpositionsecondadcchannel
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: Analog Volt 5
      - value: 2
        label: Analog Volt 6
      - value: 3
        label: Analog Volt 7
      - value: 4
        label: Analog Volt 8
      - value: 5
        label: Analog Volt 9
      - value: 6
        label: Analog Volt 10
      - value: 7
        label: Analog Volt 11
      - value: 8
        label: Battery Sense
      - value: 9
        label: Analog Temp 3
      - value: 10
        label: Analog Temp 4
      - value: 11
        label: Analog Volt 1
      - value: 12
        label: Analog Volt 2
      - value: 13
        label: Analog Volt 3
      - value: 14
        label: Analog Volt 4
      - value: 15
        label: Analog Temp 1
      - value: 16
        label: Analog Temp 2
      - value: 17
        label: INVALID
      - value: 18
        label: INVALID
      - value: 19
        label: INVALID
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      label: Accelerator position secondary sensor
    bind:
      source: config
      field: throttlePedalPositionSecondAdcChannel
  - type: scalar-field
    id: throttlepedalsecondaryupvoltage
    props:
      label: Up (idle) voltage
    bind:
      source: config
      field: throttlePedalSecondaryUpVoltage
  - type: scalar-field
    id: throttlepedalsecondarywotvoltage
    props:
      label: Down (WOT) voltage
    bind:
      source: config
      field: throttlePedalSecondaryWOTVoltage
  - type: text
    props:
      text: 'Кнопка: Grab Idle/Up (cmd_calibrate_pedal_up)'
      variant: hint
  - type: text
    props:
      text: 'Кнопка: Grab WOT/Down (cmd_calibrate_pedal_down)'
      variant: hint
  - type: scalar-field
    id: ppsexpaveragealpha
    props:
      label: Accelerator Exp Average
    bind:
      source: config
      field: ppsExpAverageAlpha
  - type: section
    props:
      title: TPS/PPS Limits
    children:
    - type: scalar-field
      id: tpserrordetectiontoolow
      props:
        label: TPS/PPS minimum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooLow
    - type: scalar-field
      id: tpserrordetectiontoohigh
      props:
        label: TPS/PPS maximum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooHigh
    - type: scalar-field
      id: etbsplit
      props:
        label: TPS/PPS Error Detection Threshold
      bind:
        source: config
        field: etbSplit
  - type: section
    props:
      title: Pedal Position Sensors special cases
    children:
    - type: enum-field
      id: usefordredundantpps
      props:
        options:
        - value: 0
          label: no
        - value: 1
          label: yes
        label: Ford/Toyota redundant PPS mode
      bind:
        source: config
        field: useFordRedundantPps
    - type: scalar-field
      id: ppssecondarymaximum
      props:
        label: Secondary PPS maximum
      bind:
        source: config
        field: ppsSecondaryMaximum
- type: section
  props:
    title: pedalGauges
