id: pedalSensor.panel
description: Accelerator pedal
source:
  ini_dialog: pedalSensor
  menu_path: Sensors › Chassis sensors › Accelerator pedal
children:
- type: section
  props:
    title: Accelerator pedal
  children:
  - type: enum-field
    id: throttlepedalpositionadcchannel
    props:
      label: Accelerator position sensor
      options:
      - value: 0
        label: NONE
      - value: 1
        label: Analog Volt 5
      - value: 2
        label: Analog Volt 6
      - value: 3
        label: Analog Volt 7
      - value: 4
        label: Analog Volt 8
      - value: 5
        label: Analog Volt 9
      - value: 6
        label: Analog Volt 10
      - value: 7
        label: Analog Volt 11
      - value: 8
        label: Battery Sense
      - value: 9
        label: Analog Temp 3
      - value: 10
        label: Analog Temp 4
      - value: 11
        label: Analog Volt 1
      - value: 12
        label: Analog Volt 2
      - value: 13
        label: Analog Volt 3
      - value: 14
        label: Analog Volt 4
      - value: 15
        label: Analog Temp 1
      - value: 16
        label: Analog Temp 2
    bind:
      source: config
      field: throttlePedalPositionAdcChannel
  - type: scalar-field
    id: throttlepedalupvoltage
    props:
      label: Up (idle) voltage
    bind:
      source: config
      field: throttlePedalUpVoltage
  - type: text
    props:
      variant: hint
      text: 'Кнопка: Grab Idle/Up (cmd_calibrate_pedal_up)'
  - type: scalar-field
    id: throttlepedalwotvoltage
    props:
      label: Down (WOT) voltage
    bind:
      source: config
      field: throttlePedalWOTVoltage
  - type: text
    props:
      text: 'Кнопка: Grab WOT/Down (cmd_calibrate_pedal_down)'
      variant: hint
  - type: enum-field
    id: throttlepedalpositionsecondadcchannel
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: Analog Volt 5
      - value: 2
        label: Analog Volt 6
      - value: 3
        label: Analog Volt 7
      - value: 4
        label: Analog Volt 8
      - value: 5
        label: Analog Volt 9
      - value: 6
        label: Analog Volt 10
      - value: 7
        label: Analog Volt 11
      - value: 8
        label: Battery Sense
      - value: 9
        label: Analog Temp 3
      - value: 10
        label: Analog Temp 4
      - value: 11
        label: Analog Volt 1
      - value: 12
        label: Analog Volt 2
      - value: 13
        label: Analog Volt 3
      - value: 14
        label: Analog Volt 4
      - value: 15
        label: Analog Temp 1
      - value: 16
        label: Analog Temp 2
      label: Accelerator position 2nd sensor
    bind:
      source: config
      field: throttlePedalPositionSecondAdcChannel
  - type: scalar-field
    id: throttlepedalsecondaryupvoltage
    props:
      label: Up (idle) voltage
    bind:
      source: config
      field: throttlePedalSecondaryUpVoltage
  - type: scalar-field
    id: throttlepedalsecondarywotvoltage
    props:
      label: Down (WOT) voltage
    bind:
      source: config
      field: throttlePedalSecondaryWOTVoltage
  - type: scalar-field
    id: ppsexpaveragealpha
    props:
      label: Accelerator Exp Average
    bind:
      source: config
      field: ppsExpAverageAlpha
  - type: enum-field
    id: usefordredundantpps
    props:
      label: Ford/Toyota redundant PPS mode
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: useFordRedundantPps
  - type: scalar-field
    id: ppssecondarymaximum
    props:
      label: Secondary PPS maximum
    bind:
      source: config
      field: ppsSecondaryMaximum
  - type: section
    props:
      title: TPS/PPS Limits
    children:
    - type: scalar-field
      id: tpserrordetectiontoolow
      props:
        label: TPS/PPS minimum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooLow
    - type: scalar-field
      id: tpserrordetectiontoohigh
      props:
        label: TPS/PPS maximum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooHigh
    - type: scalar-field
      id: etbsplit
      props:
        label: TPS/PPS Error Detection Threshold
      bind:
        source: config
        field: etbSplit
    - type: enum-field
      id: usefordredundanttps
      props:
        options:
        - value: 0
          label: 'false'
        - value: 1
          label: 'true'
        label: Ford/Toyota redundant TPS mode
      bind:
        source: config
        field: useFordRedundantTps
    - type: scalar-field
      id: tpssecondarymaximum
      props:
        label: Secondary TPS maximum
      bind:
        source: config
        field: tpsSecondaryMaximum
- type: section
  props:
    title: pedalGauges
