id: primingFuelPulsePanel.panel
description: Priming fuel pulse
source:
  ini_dialog: primingFuelPulsePanel
  menu_path: Cranking › Priming pulse
children:
- type: scalar-field
  id: primingdelay
  props:
    label: Priming delay
  bind:
    source: config
    field: primingDelay
- type: config-table
  id: primingpulse
  props:
    xLabel: Coolant
    yLabel: Prime Pulse
    yBins: primeValues
    title: Priming pulse fuel mass
    variant: curve
    xBins: primeBins
