id: scriptTable4TblSettings.panel
description: 'Script Table #4'
source:
  ini_dialog: scriptTable4TblSettings
  menu_path: 'Advanced › Lua Calibrations › Script Table #4'
children:
- type: scalar-field
  id: scripttablename4
  props:
    label: Name
  bind:
    source: config
    field: scriptTableName4
- type: config-table
  id: scripttable4tbl
  props:
    yBins: scriptTable4LoadBins
    variant: table
    xBins: scriptTable4RpmBins
    zBins: scriptTable4
    title: 'Script Table #4'
