id: scriptCurve6Settings.panel
description: 'Script Curve #6'
source:
  ini_dialog: scriptCurve6Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #6'
children:
- type: string-field
  id: scriptcurvename6
  props:
    maxLength: 16
    label: Name
  bind:
    source: config
    field: scriptCurveName6
- type: curve
  id: scriptcurve6
  props:
    title: 'Script Curve #6'
    xLabel: X
    yLabel: Y
  bind:
    source: config
    params:
      yBins: scriptCurve6
      xBins: scriptCurve6Bins
