id: scriptSetting.panel
description: Setting
source:
  ini_dialog: scriptSetting
  menu_path: Advanced › Lua Calibrations › Lua Script Settings
children:
- type: text
  props:
    text: Use rusEFI console for Lua script editing
    variant: hint
- type: scalar-field
  id: set-number-is-not-associated-with-the-output-number
  props:
    label: Set number is not associated with the output number.
  bind:
    source: config
    field: Set number is not associated with the output number.
- type: scalar-field
  id: set-number--only-the-cell-number-with-some-numbers
  props:
    label: Set number, only the cell number with some numbers.
  bind:
    source: config
    field: Set number, only the cell number with some numbers.
- type: scalar-field
  id: scriptsettingname1
  props:
    label: 'Name #1'
  bind:
    source: config
    field: scriptSettingName1
- type: scalar-field
  id: scriptsetting1
  props:
    label: 'Setting #1'
  bind:
    source: config
    field: scriptSetting1
- type: scalar-field
  id: scriptsettingname2
  props:
    label: 'Name #2'
  bind:
    source: config
    field: scriptSettingName2
- type: scalar-field
  id: scriptsetting2
  props:
    label: 'Setting #2'
  bind:
    source: config
    field: scriptSetting2
- type: scalar-field
  id: scriptsettingname3
  props:
    label: 'Name #3'
  bind:
    source: config
    field: scriptSettingName3
- type: scalar-field
  id: scriptsetting3
  props:
    label: 'Setting #3'
  bind:
    source: config
    field: scriptSetting3
- type: scalar-field
  id: scriptsettingname4
  props:
    label: 'Name #4'
  bind:
    source: config
    field: scriptSettingName4
- type: scalar-field
  id: scriptsetting4
  props:
    label: 'Setting #4'
  bind:
    source: config
    field: scriptSetting4
- type: scalar-field
  id: scriptsettingname5
  props:
    label: 'Name #5'
  bind:
    source: config
    field: scriptSettingName5
- type: scalar-field
  id: scriptsetting5
  props:
    label: 'Setting #5'
  bind:
    source: config
    field: scriptSetting5
- type: scalar-field
  id: scriptsettingname6
  props:
    label: 'Name #6'
  bind:
    source: config
    field: scriptSettingName6
- type: scalar-field
  id: scriptsetting6
  props:
    label: 'Setting #6'
  bind:
    source: config
    field: scriptSetting6
