id: scriptTable3TblSettings.panel
description: 'Script Table #3'
source:
  ini_dialog: scriptTable3TblSettings
  menu_path: 'Advanced › Lua Calibrations › Script Table #3'
children:
- type: string-field
  id: scripttablename3
  props:
    label: Name
    maxLength: 16
  bind:
    source: config
    field: scriptTableName3
- type: config-table
  id: scripttable3tbl
  props:
    variant: table
    title: 'Script Table #3'
  bind:
    source: config
    params:
      yBins: scriptTable3LoadBins
      zBins: scriptTable3
      xBins: scriptTable3RpmBins
