id: scriptCurve4Settings.panel
description: 'Script Curve #4'
source:
  ini_dialog: scriptCurve4Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #4'
children:
- type: string-field
  id: scriptcurvename4
  props:
    maxLength: 16
    label: Name
  bind:
    source: config
    field: scriptCurveName4
- type: curve
  id: scriptcurve4
  props:
    title: 'Script Curve #4'
    xLabel: X
    yLabel: Y
  bind:
    source: config
    params:
      xBins: scriptCurve4Bins
      yBins: scriptCurve4
