id: scriptCurve3Settings.panel
description: 'Script Curve #3'
source:
  ini_dialog: scriptCurve3Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #3'
children:
- type: scalar-field
  id: scriptcurvename3
  props:
    label: Name
  bind:
    source: config
    field: scriptCurveName3
- type: config-table
  id: scriptcurve3
  props:
    title: 'Script Curve #3'
    xBins: scriptCurve3Bins
    xLabel: X
    yBins: scriptCurve3
    variant: curve
    yLabel: Y
