id: scriptCurve3Settings.panel
description: 'Script Curve #3'
source:
  ini_dialog: scriptCurve3Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #3'
children:
- type: string-field
  id: scriptcurvename3
  props:
    label: Name
    maxLength: 16
  bind:
    source: config
    field: scriptCurveName3
- type: curve
  id: scriptcurve3
  props:
    title: 'Script Curve #3'
    xLabel: X
    yLabel: Y
  bind:
    source: config
    params:
      yBins: scriptCurve3
      xBins: scriptCurve3Bins
