id: scriptCurve4Settings.panel
description: 'Script Curve #4'
source:
  ini_dialog: scriptCurve4Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #4'
children:
- type: scalar-field
  id: scriptcurvename4
  props:
    label: Name
  bind:
    source: config
    field: scriptCurveName4
- type: config-table
  id: scriptcurve4
  props:
    yLabel: Y
    xLabel: X
    variant: curve
    xBins: scriptCurve4Bins
    title: 'Script Curve #4'
    yBins: scriptCurve4
