id: scriptCurve2Settings.panel
description: 'Script Curve #2'
source:
  ini_dialog: scriptCurve2Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #2'
children:
- type: string-field
  id: scriptcurvename2
  props:
    maxLength: 16
    label: Name
  bind:
    source: config
    field: scriptCurveName2
- type: curve
  id: scriptcurve2
  props:
    yLabel: Y
    xLabel: X
    xBins: scriptCurve2Bins
    title: 'Script Curve #2'
    yBins: scriptCurve2
