id: scriptTable4TblSettings.panel
description: 'Script Table #4'
source:
  ini_dialog: scriptTable4TblSettings
  menu_path: 'Advanced › Lua Calibrations › Script Table #4'
children:
- type: string-field
  id: scripttablename4
  props:
    maxLength: 16
    label: Name
  bind:
    source: config
    field: scriptTableName4
- type: config-table
  id: scripttable4tbl
  props:
    xBins: scriptTable4RpmBins
    title: 'Script Table #4'
    yBins: scriptTable4LoadBins
    zBins: scriptTable4
    variant: table
