id: scriptCurve1Settings.panel
description: 'Script Curve #1'
source:
  ini_dialog: scriptCurve1Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #1'
children:
- type: string-field
  id: scriptcurvename1
  props:
    maxLength: 16
    label: Name
  bind:
    source: config
    field: scriptCurveName1
- type: curve
  id: scriptcurve1
  props:
    xBins: scriptCurve1Bins
    yLabel: Y
    yBins: scriptCurve1
    title: 'Script Curve #1'
    xLabel: X
