id: scriptCurve5Settings.panel
description: 'Script Curve #5'
source:
  ini_dialog: scriptCurve5Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #5'
children:
- type: scalar-field
  id: scriptcurvename5
  props:
    label: Name
  bind:
    source: config
    field: scriptCurveName5
- type: curve
  id: scriptcurve5
  props:
    xLabel: X
    yBins: scriptCurve5
    title: 'Script Curve #5'
    xBins: scriptCurve5Bins
    yLabel: Y
