id: scriptCurve5Settings.panel
description: 'Script Curve #5'
source:
  ini_dialog: scriptCurve5Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #5'
children:
- type: string-field
  id: scriptcurvename5
  props:
    label: Name
    maxLength: 16
  bind:
    source: config
    field: scriptCurveName5
- type: curve
  id: scriptcurve5
  props:
    title: 'Script Curve #5'
    xLabel: X
    yLabel: Y
  bind:
    source: config
    params:
      yBins: scriptCurve5
      xBins: scriptCurve5Bins
