id: scriptCurve2Settings.panel
description: 'Script Curve #2'
source:
  ini_dialog: scriptCurve2Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #2'
children:
- type: scalar-field
  id: scriptcurvename2
  props:
    label: Name
  bind:
    source: config
    field: scriptCurveName2
- type: curve
  id: scriptcurve2
  props:
    xLabel: X
    title: 'Script Curve #2'
    xBins: scriptCurve2Bins
    yLabel: Y
    yBins: scriptCurve2
