id: scriptCurve2Settings.panel
description: 'Script Curve #2'
source:
  ini_dialog: scriptCurve2Settings
  menu_path: 'Advanced › Lua Calibrations › Script Curve #2'
children:
- type: string-field
  id: scriptcurvename2
  props:
    label: Name
    maxLength: 16
  bind:
    source: config
    field: scriptCurveName2
- type: curve
  id: scriptcurve2
  props:
    title: 'Script Curve #2'
    yLabel: Y
    xLabel: X
  bind:
    source: config
    params:
      yBins: scriptCurve2
      xBins: scriptCurve2Bins
