id: scriptTable2TblSettings.panel
description: 'Script Table #2'
source:
  ini_dialog: scriptTable2TblSettings
  menu_path: 'Advanced › Lua Calibrations › Script Table #2'
children:
- type: string-field
  id: scripttablename2
  props:
    label: Name
    maxLength: 16
  bind:
    source: config
    field: scriptTableName2
- type: config-table
  id: scripttable2tbl
  props:
    variant: table
    xBins: scriptTable2RpmBins
    yBins: scriptTable2LoadBins
    title: 'Script Table #2'
    zBins: scriptTable2
