id: scriptTable3TblSettings.panel
description: 'Script Table #3'
source:
  ini_dialog: scriptTable3TblSettings
  menu_path: 'Advanced › Lua Calibrations › Script Table #3'
children:
- type: scalar-field
  id: scripttablename3
  props:
    label: Name
  bind:
    source: config
    field: scriptTableName3
- type: config-table
  id: scripttable3tbl
  props:
    variant: table
    zBins: scriptTable3
    yBins: scriptTable3LoadBins
    title: 'Script Table #3'
    xBins: scriptTable3RpmBins
