id: smLaunchControl.panel
description: Launch Control
source:
  ini_dialog: smLaunchControl
  menu_path: Advanced › Launch Control
children:
- type: section
  props:
    title: Launch Control Settings
  children:
  - type: text
    props:
      text: Also known as Rolling antilag
      variant: hint
  - type: enum-field
    id: launchcontrolenabled
    props:
      label: Enable Launch Control
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: launchControlEnabled
  - type: enum-field
    id: launchactivationmode
    props:
      label: Activation Mode
      options:
      - value: 0
        label: Launch Button
      - value: 1
        label: Clutch Down Switch
      - value: 2
        label: Speed Based
      - value: 3
        label: Brake Pedal
      - value: 4
        label: Lua
      - value: 5
        label: INVALID
      - value: 6
        label: INVALID
      - value: 7
        label: INVALID
    bind:
      source: config
      field: launchActivationMode
  - type: enum-field
    id: launchactivatepin
    props:
      options:
      - value: 0
        label: NONE
      - value: 1
        label: INVALID
      - value: 2
        label: Analog Volt 5
      - value: 3
        label: Analog Volt 6
      - value: 4
        label: Analog Volt 7
      - value: 5
        label: Analog Volt 8
      - value: 6
        label: Analog Volt 9
      - value: 7
        label: Analog Volt 10
      - value: 8
        label: Analog Volt 11
      - value: 9
        label: INVALID
      - value: 10
        label: INVALID
      - value: 11
        label: INVALID
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: Analog Temp 3
      - value: 19
        label: Analog Temp 4
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      - value: 32
        label: INVALID
      - value: 33
        label: INVALID
      - value: 34
        label: Analog Volt 1
      - value: 35
        label: Analog Volt 2
      - value: 36
        label: Analog Volt 3
      - value: 37
        label: Analog Volt 4
      - value: 38
        label: Analog Temp 1
      - value: 39
        label: Analog Temp 2
      - value: 40
        label: Digital 1
      - value: 41
        label: INVALID
      - value: 42
        label: INVALID
      - value: 43
        label: INVALID
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: INVALID
      - value: 54
        label: INVALID
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: INVALID
      - value: 58
        label: INVALID
      - value: 59
        label: INVALID
      - value: 60
        label: INVALID
      - value: 61
        label: INVALID
      - value: 62
        label: INVALID
      - value: 63
        label: INVALID
      - value: 64
        label: INVALID
      - value: 65
        label: INVALID
      - value: 66
        label: INVALID
      - value: 67
        label: INVALID
      - value: 68
        label: INVALID
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: Digital 2
      - value: 78
        label: Digital 3
      - value: 79
        label: Digital 5
      - value: 80
        label: Digital 4
      - value: 81
        label: Digital 6
      label: Launch Button
    bind:
      source: config
      field: launchActivatePin
  - type: enum-field
    id: launchactivatepinmode
    props:
      label: Launch Button mode
      options:
      - value: 0
        label: DEFAULT
      - value: 1
        label: PULLUP
      - value: 2
        label: PULLDOWN
      - value: 3
        label: INVALID
      - value: 4
        label: INVERTED DEFAULT
      - value: 5
        label: INVERTED PULLUP
      - value: 6
        label: INVERTED PULLDOWN
    bind:
      source: config
      field: launchActivatePinMode
  - type: enum-field
    id: clutchdownpin
    props:
      label: Clutch Down
      options:
      - value: 0
        label: NONE
      - value: 1
        label: INVALID
      - value: 2
        label: Analog Volt 5
      - value: 3
        label: Analog Volt 6
      - value: 4
        label: Analog Volt 7
      - value: 5
        label: Analog Volt 8
      - value: 6
        label: Analog Volt 9
      - value: 7
        label: Analog Volt 10
      - value: 8
        label: Analog Volt 11
      - value: 9
        label: INVALID
      - value: 10
        label: INVALID
      - value: 11
        label: INVALID
      - value: 12
        label: INVALID
      - value: 13
        label: INVALID
      - value: 14
        label: INVALID
      - value: 15
        label: INVALID
      - value: 16
        label: INVALID
      - value: 17
        label: INVALID
      - value: 18
        label: Analog Temp 3
      - value: 19
        label: Analog Temp 4
      - value: 20
        label: INVALID
      - value: 21
        label: INVALID
      - value: 22
        label: INVALID
      - value: 23
        label: INVALID
      - value: 24
        label: INVALID
      - value: 25
        label: INVALID
      - value: 26
        label: INVALID
      - value: 27
        label: INVALID
      - value: 28
        label: INVALID
      - value: 29
        label: INVALID
      - value: 30
        label: INVALID
      - value: 31
        label: INVALID
      - value: 32
        label: INVALID
      - value: 33
        label: INVALID
      - value: 34
        label: Analog Volt 1
      - value: 35
        label: Analog Volt 2
      - value: 36
        label: Analog Volt 3
      - value: 37
        label: Analog Volt 4
      - value: 38
        label: Analog Temp 1
      - value: 39
        label: Analog Temp 2
      - value: 40
        label: Digital 1
      - value: 41
        label: INVALID
      - value: 42
        label: INVALID
      - value: 43
        label: INVALID
      - value: 44
        label: INVALID
      - value: 45
        label: INVALID
      - value: 46
        label: INVALID
      - value: 47
        label: INVALID
      - value: 48
        label: INVALID
      - value: 49
        label: INVALID
      - value: 50
        label: INVALID
      - value: 51
        label: INVALID
      - value: 52
        label: INVALID
      - value: 53
        label: INVALID
      - value: 54
        label: INVALID
      - value: 55
        label: INVALID
      - value: 56
        label: INVALID
      - value: 57
        label: INVALID
      - value: 58
        label: INVALID
      - value: 59
        label: INVALID
      - value: 60
        label: INVALID
      - value: 61
        label: INVALID
      - value: 62
        label: INVALID
      - value: 63
        label: INVALID
      - value: 64
        label: INVALID
      - value: 65
        label: INVALID
      - value: 66
        label: INVALID
      - value: 67
        label: INVALID
      - value: 68
        label: INVALID
      - value: 69
        label: INVALID
      - value: 70
        label: INVALID
      - value: 71
        label: INVALID
      - value: 72
        label: INVALID
      - value: 73
        label: INVALID
      - value: 74
        label: INVALID
      - value: 75
        label: INVALID
      - value: 76
        label: INVALID
      - value: 77
        label: Digital 2
      - value: 78
        label: Digital 3
      - value: 79
        label: Digital 5
      - value: 80
        label: Digital 4
      - value: 81
        label: Digital 6
    bind:
      source: config
      field: clutchDownPin
  - type: enum-field
    id: clutchdownpinmode
    props:
      options:
      - value: 0
        label: DEFAULT
      - value: 1
        label: PULLUP
      - value: 2
        label: PULLDOWN
      - value: 3
        label: INVALID
      - value: 4
        label: INVERTED DEFAULT
      - value: 5
        label: INVERTED PULLUP
      - value: 6
        label: INVERTED PULLDOWN
      label: Clutch Down mode
    bind:
      source: config
      field: clutchDownPinMode
  - type: scalar-field
    id: launchspeedthreshold
    props:
      label: Speed Threshold
    bind:
      source: config
      field: launchSpeedThreshold
  - type: scalar-field
    id: launchrpm
    props:
      label: Launch RPM
    bind:
      source: config
      field: launchRpm
  - type: scalar-field
    id: launchrpmwindow
    props:
      label: Launch Control Window
    bind:
      source: config
      field: launchRpmWindow
  - type: scalar-field
    id: launchtpsthreshold
    props:
      label: TPS Threshold
    bind:
      source: config
      field: launchTpsThreshold
  - type: enum-field
    id: enablelaunchretard
    props:
      label: Ignition Retard enable
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: enableLaunchRetard
  - type: scalar-field
    id: launchtimingretard
    props:
      label: Ignition Retard
    bind:
      source: config
      field: launchTimingRetard
  - type: scalar-field
    id: launchfueladderpercent
    props:
      label: Fuel Added %
    bind:
      source: config
      field: launchFuelAdderPercent
  - type: enum-field
    id: launchsmoothretard
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Smooth Retard Mode
    bind:
      source: config
      field: launchSmoothRetard
  - type: scalar-field
    id: launchcorrectionsendrpm
    props:
      label: Launch Corrections End RPM
    bind:
      source: config
      field: launchCorrectionsEndRpm
  - type: scalar-field
    id: hard-cut-mode
    props:
      label: Hard Cut Mode
    bind:
      source: config
      field: Hard Cut Mode
  - type: enum-field
    id: launchsparkcutenable
    props:
      label: Ignition Cut
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
    bind:
      source: config
      field: launchSparkCutEnable
  - type: scalar-field
    id: initialignitioncutpercent
    props:
      label: Initial Ignition Cut %
    bind:
      source: config
      field: initialIgnitionCutPercent
  - type: scalar-field
    id: finalignitioncutpercentbeforelaunch
    props:
      label: Final Ignition Cut % Before launch
    bind:
      source: config
      field: finalIgnitionCutPercentBeforeLaunch
  - type: enum-field
    id: launchfuelcutenable
    props:
      options:
      - value: 0
        label: 'false'
      - value: 1
        label: 'true'
      label: Fuel Cut
    bind:
      source: config
      field: launchFuelCutEnable
- type: section
  props:
    title: launch_control_state
  children:
  - type: text
    props:
      text: Панель «launch_control_stateIndicatorPanel» — нет определения в INI
      variant: hint
