id: softwareKnock.panel
description: Software Knock
source:
  ini_dialog: softwareKnock
  menu_path: Ignition › Cylinder ign trims › Knock Control
children:
- type: section
  props:
    title: softwareKnockLeft
  children:
  - type: section
    props:
      title: Sense
    children:
    - type: enum-field
      id: enablesoftwareknock
      props:
        label: Knock sensing
        options:
        - value: 0
          label: disabled
        - value: 1
          label: enabled
      bind:
        source: config
        field: enableSoftwareKnock
    - type: scalar-field
      id: cylinderbore
      props:
        label: Cylinder Bore
      bind:
        source: config
        field: cylinderBore
    - type: scalar-field
      id: knockfrequency
      props:
        label: Estimated Knock Frequency
      bind:
        source: config
        field: knockFrequency
    - type: enum-field
      id: knockdetectionusedoublefrequency
      props:
        options:
        - value: 0
          label: first harmonic
        - value: 1
          label: second harmonic
        label: Detection mode
      bind:
        source: config
        field: knockDetectionUseDoubleFrequency
    - type: scalar-field
      id: knockdetectionwindowstart
      props:
        label: Detection Window Start
      bind:
        source: config
        field: knockDetectionWindowStart
    - type: scalar-field
      id: knocksamplingduration
      props:
        label: Sampling Duration
      bind:
        source: config
        field: knockSamplingDuration
    - type: enum-field
      id: enableknockspectrogram
      props:
        label: Enable Knock Spectrogram
        options:
        - value: 0
          label: no
        - value: 1
          label: yes
      bind:
        source: config
        field: enableKnockSpectrogram
    - type: enum-field
      id: enableknockspectrogramfilter
      props:
        label: Enable Knock Spectrogram Filter
        options:
        - value: 0
          label: no
        - value: 1
          label: yes
      bind:
        source: config
        field: enableKnockSpectrogramFilter
    - type: scalar-field
      id: knockspectrumsensitivity
      props:
        label: Knock Spectrum Sensitivity
      bind:
        source: config
        field: knockSpectrumSensitivity
    - type: section
      props:
        title: Select the nearest sensor for each cylinder
  - type: section
    props:
      title: Response
    children:
    - type: scalar-field
      id: knockretardaggression
      props:
        label: Retard Aggression
      bind:
        source: config
        field: knockRetardAggression
    - type: scalar-field
      id: knockretardreapplyrate
      props:
        label: Retard Reapply Rate
      bind:
        source: config
        field: knockRetardReapplyRate
    - type: scalar-field
      id: knockfueltrimaggression
      props:
        label: Fuel Trim Aggression
      bind:
        source: config
        field: knockFuelTrimAggression
    - type: scalar-field
      id: knockfueltrimreapplyrate
      props:
        label: Fuel Trim Reapply Rate
      bind:
        source: config
        field: knockFuelTrimReapplyRate
    - type: scalar-field
      id: knockfueltrim
      props:
        label: Fuel Trim
      bind:
        source: config
        field: knockFuelTrim
    - type: scalar-field
      id: knocksuppressmintps
      props:
        label: Suppress Min Tps
      bind:
        source: config
        field: knockSuppressMinTps
- type: curve
  id: knockthresholdcurve
  props:
    xBins: knockNoiseRpmBins
    yBins: knockBaseNoise
    title: Engine Knock Threshold RPM Based
    xLabel: RPM
    yLabel: Threshold
