id: speedSensor.panel
description: Speed sensor
source:
  ini_dialog: speedSensor
  menu_path: Sensors › Chassis sensors › Vehicle speed sensor
children:
- type: section
  props:
    title: speedSensorLeft
  children:
  - type: section
    props:
      title: Speed sensor
    children:
    - type: enum-field
      id: vehiclespeedsensorinputpin
      props:
        label: Input
        options:
        - value: 0
          label: NONE
        - value: 1
          label: INVALID
        - value: 2
          label: INVALID
        - value: 3
          label: INVALID
        - value: 4
          label: INVALID
        - value: 5
          label: INVALID
        - value: 6
          label: INVALID
        - value: 7
          label: INVALID
        - value: 8
          label: INVALID
        - value: 9
          label: INVALID
        - value: 10
          label: INVALID
        - value: 11
          label: INVALID
        - value: 12
          label: INVALID
        - value: 13
          label: INVALID
        - value: 14
          label: INVALID
        - value: 15
          label: INVALID
        - value: 16
          label: INVALID
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
        - value: 32
          label: INVALID
        - value: 33
          label: INVALID
        - value: 34
          label: INVALID
        - value: 35
          label: INVALID
        - value: 36
          label: INVALID
        - value: 37
          label: INVALID
        - value: 38
          label: INVALID
        - value: 39
          label: INVALID
        - value: 40
          label: Digital 1
        - value: 41
          label: INVALID
        - value: 42
          label: INVALID
        - value: 43
          label: INVALID
        - value: 44
          label: INVALID
        - value: 45
          label: INVALID
        - value: 46
          label: INVALID
        - value: 47
          label: INVALID
        - value: 48
          label: INVALID
        - value: 49
          label: INVALID
        - value: 50
          label: INVALID
        - value: 51
          label: INVALID
        - value: 52
          label: INVALID
        - value: 53
          label: INVALID
        - value: 54
          label: INVALID
        - value: 55
          label: INVALID
        - value: 56
          label: INVALID
        - value: 57
          label: INVALID
        - value: 58
          label: INVALID
        - value: 59
          label: INVALID
        - value: 60
          label: INVALID
        - value: 61
          label: INVALID
        - value: 62
          label: INVALID
        - value: 63
          label: INVALID
        - value: 64
          label: INVALID
        - value: 65
          label: INVALID
        - value: 66
          label: INVALID
        - value: 67
          label: INVALID
        - value: 68
          label: INVALID
        - value: 69
          label: INVALID
        - value: 70
          label: INVALID
        - value: 71
          label: INVALID
        - value: 72
          label: INVALID
        - value: 73
          label: VR 1
        - value: 74
          label: VR 2
        - value: 75
          label: INVALID
        - value: 76
          label: INVALID
        - value: 77
          label: Digital 2
        - value: 78
          label: Digital 3
        - value: 79
          label: Digital 5
        - value: 80
          label: Digital 4
        - value: 81
          label: Digital 6
        - value: 82
          label: INVALID
        - value: 83
          label: INVALID
        - value: 84
          label: INVALID
        - value: 85
          label: INVALID
        - value: 86
          label: INVALID
        - value: 87
          label: INVALID
        - value: 88
          label: INVALID
        - value: 89
          label: INVALID
        - value: 90
          label: INVALID
        - value: 91
          label: INVALID
        - value: 92
          label: INVALID
        - value: 93
          label: INVALID
        - value: 94
          label: INVALID
        - value: 95
          label: INVALID
        - value: 96
          label: INVALID
        - value: 97
          label: INVALID
        - value: 98
          label: INVALID
        - value: 99
          label: INVALID
        - value: 100
          label: INVALID
        - value: 101
          label: INVALID
        - value: 102
          label: INVALID
        - value: 103
          label: INVALID
        - value: 104
          label: INVALID
        - value: 105
          label: INVALID
        - value: 106
          label: INVALID
        - value: 107
          label: INVALID
        - value: 108
          label: INVALID
        - value: 109
          label: INVALID
        - value: 110
          label: INVALID
        - value: 111
          label: INVALID
        - value: 112
          label: INVALID
        - value: 113
          label: INVALID
        - value: 114
          label: INVALID
        - value: 115
          label: INVALID
        - value: 116
          label: INVALID
        - value: 117
          label: INVALID
        - value: 118
          label: INVALID
        - value: 119
          label: INVALID
        - value: 120
          label: INVALID
        - value: 121
          label: INVALID
        - value: 122
          label: INVALID
        - value: 123
          label: INVALID
        - value: 124
          label: INVALID
        - value: 125
          label: INVALID
        - value: 126
          label: INVALID
        - value: 127
          label: INVALID
      bind:
        source: config
        field: vehicleSpeedSensorInputPin
    - type: scalar-field
      id: vssfilterreciprocal
      props:
        label: Filter parameter
      bind:
        source: config
        field: vssFilterReciprocal
    - type: scalar-field
      id: drivewheelrevperkm
      props:
        label: Wheel revolutions per kilometer
      bind:
        source: config
        field: driveWheelRevPerKm
    - type: scalar-field
      id: vssgearratio
      props:
        label: Speed sensor gear ratio
      bind:
        source: config
        field: vssGearRatio
    - type: scalar-field
      id: vsstoothcount
      props:
        label: Speed sensor tooth count
      bind:
        source: config
        field: vssToothCount
  - type: section
    props:
      title: CAN Vehicle Speed
    children:
    - type: enum-field
      id: enablecanvss
      props:
        label: Enable CAN VSS
        options:
        - value: 0
          label: no
        - value: 1
          label: yes
      bind:
        source: config
        field: enableCanVss
    - type: enum-field
      id: canvssnbctype
      props:
        options:
        - value: 0
          label: BMW_e46
        - value: 1
          label: W202
        - value: 2
          label: BMW E8x/E9x MK60e5
        - value: 3
          label: Nissan 350
        - value: 4
          label: Hyundai PB
        - value: 5
          label: Honda Civic9
        - value: 6
          label: INVALID
        - value: 7
          label: INVALID
        label: CAN VSS type
      bind:
        source: config
        field: canVssNbcType
    - type: scalar-field
      id: canvssscaling
      props:
        label: CAN VSS scaling
      bind:
        source: config
        field: canVssScaling
- type: section
  props:
    title: Gear Detection
  children:
  - type: scalar-field
    id: drivewheelrevperkm
    props:
      label: Wheel revolutions per kilometer
    bind:
      source: config
      field: driveWheelRevPerKm
  - type: scalar-field
    id: finalgearratio
    props:
      label: Final drive ratio
    bind:
      source: config
      field: finalGearRatio
  - type: scalar-field
    id: totalgearscount
    props:
      label: Forward gear count
    bind:
      source: config
      field: totalGearsCount
  - type: scalar-field
    id: gearratio1
    props:
      label: 1st gear
    bind:
      source: config
      field: gearRatio1
  - type: scalar-field
    id: gearratio2
    props:
      label: 2nd gear
    bind:
      source: config
      field: gearRatio2
  - type: scalar-field
    id: gearratio3
    props:
      label: 3rd gear
    bind:
      source: config
      field: gearRatio3
  - type: scalar-field
    id: gearratio4
    props:
      label: 4th gear
    bind:
      source: config
      field: gearRatio4
  - type: scalar-field
    id: gearratio5
    props:
      label: 5th gear
    bind:
      source: config
      field: gearRatio5
  - type: scalar-field
    id: gearratio6
    props:
      label: 6th gear
    bind:
      source: config
      field: gearRatio6
  - type: scalar-field
    id: gearratio7
    props:
      label: 7th gear
    bind:
      source: config
      field: gearRatio7
  - type: scalar-field
    id: gearratio8
    props:
      label: 8th gear
    bind:
      source: config
      field: gearRatio8
