id: stagedInjection.panel
description: Staged injection
source:
  ini_dialog: stagedInjection
  menu_path: Fuel › Cylinder fuel trims › Staged injection
children:
- type: enum-field
  id: enablestagedinjection
  props:
    label: Enable
    options:
    - value: 0
      label: disabled
    - value: 1
      label: enabled
  bind:
    source: config
    field: enableStagedInjection
- type: scalar-field
  id: injectorsecondary-flow
  props:
    label: Secondary injector flow
  bind:
    source: config
    field: injectorSecondary_flow
- type: enum-field
  id: secondaryinjectorcompensationmode
  props:
    options:
    - value: 0
      label: None
    - value: 1
      label: Fixed rail pressure
    - value: 2
      label: Sensed Rail Pressure
    - value: 3
      label: HPFP fuel mass compensation
    label: Secondary injector flow compensation mode
  bind:
    source: config
    field: secondaryInjectorCompensationMode
- type: scalar-field
  id: secondaryinjectorfuelreferencepressure
  props:
    label: Secondary injector reference pressure
  bind:
    source: config
    field: secondaryInjectorFuelReferencePressure
- type: config-table
  id: injectorssecondarydeadtime
  props:
    variant: table
    xLabel: Battery
    title: Secondary injector dead time
    yLabel: Pressure
  bind:
    source: config
    params:
      yBins: injectorSecondary_battLagCorrPressBins
      zBins: injectorSecondary_battLagCorrTable
      xBins: injectorSecondary_battLagCorrBattBins
