id: tpsSensor.panel
description: TPS
source:
  ini_dialog: tpsSensor
  menu_path: Sensors › Chassis sensors › TPS
children:
- type: section
  props:
    title: tpsSensorLeft
  children:
  - type: section
    props:
      title: 'Throttle Body #1 Sensor(s)'
    children:
    - type: enum-field
      id: tps1-1adcchannel
      props:
        label: Primary sensor input
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
      bind:
        source: config
        field: tps1_1AdcChannel
    - type: scalar-field
      id: tpsmin
      props:
        label: Primary closed
      bind:
        source: config
        field: tpsMin
    - type: scalar-field
      id: tpsmax
      props:
        label: Primary open
      bind:
        source: config
        field: tpsMax
    - type: enum-field
      id: tps1-2adcchannel
      props:
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
        label: Secondary sensor input
      bind:
        source: config
        field: tps1_2AdcChannel
    - type: scalar-field
      id: tps1secondarymin
      props:
        label: Secondary closed
      bind:
        source: config
        field: tps1SecondaryMin
    - type: scalar-field
      id: tps1secondarymax
      props:
        label: Secondary open
      bind:
        source: config
        field: tps1SecondaryMax
    - type: text
      props:
        variant: hint
        text: 'Кнопка: Auto Calibrate ETB 1 (cmd_etb_auto_calibrate)'
    - type: text
      props:
        text: 'Кнопка: Grab Closed Throttle voltage (cmd_calibrate_tps_closed)'
        variant: hint
    - type: text
      props:
        variant: hint
        text: 'Кнопка: Grab Fully Opened Throttle voltage  (cmd_calibrate_tps_open)'
  - type: section
    props:
      title: 'Throttle Body #2 Sensor(s)'
    children:
    - type: enum-field
      id: tps2-1adcchannel
      props:
        label: Primary sensor
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
      bind:
        source: config
        field: tps2_1AdcChannel
    - type: scalar-field
      id: tps2min
      props:
        label: Primary min
      bind:
        source: config
        field: tps2Min
    - type: scalar-field
      id: tps2max
      props:
        label: Primary max
      bind:
        source: config
        field: tps2Max
    - type: enum-field
      id: tps2-2adcchannel
      props:
        label: Secondary sensor
        options:
        - value: 0
          label: NONE
        - value: 1
          label: Analog Volt 5
        - value: 2
          label: Analog Volt 6
        - value: 3
          label: Analog Volt 7
        - value: 4
          label: Analog Volt 8
        - value: 5
          label: Analog Volt 9
        - value: 6
          label: Analog Volt 10
        - value: 7
          label: Analog Volt 11
        - value: 8
          label: Battery Sense
        - value: 9
          label: Analog Temp 3
        - value: 10
          label: Analog Temp 4
        - value: 11
          label: Analog Volt 1
        - value: 12
          label: Analog Volt 2
        - value: 13
          label: Analog Volt 3
        - value: 14
          label: Analog Volt 4
        - value: 15
          label: Analog Temp 1
        - value: 16
          label: Analog Temp 2
        - value: 17
          label: INVALID
        - value: 18
          label: INVALID
        - value: 19
          label: INVALID
        - value: 20
          label: INVALID
        - value: 21
          label: INVALID
        - value: 22
          label: INVALID
        - value: 23
          label: INVALID
        - value: 24
          label: INVALID
        - value: 25
          label: INVALID
        - value: 26
          label: INVALID
        - value: 27
          label: INVALID
        - value: 28
          label: INVALID
        - value: 29
          label: INVALID
        - value: 30
          label: INVALID
        - value: 31
          label: INVALID
      bind:
        source: config
        field: tps2_2AdcChannel
    - type: scalar-field
      id: tps2secondarymin
      props:
        label: Secondary min
      bind:
        source: config
        field: tps2SecondaryMin
    - type: scalar-field
      id: tps2secondarymax
      props:
        label: Secondary max
      bind:
        source: config
        field: tps2SecondaryMax
    - type: text
      props:
        variant: hint
        text: 'Кнопка: Auto Calibrate ETB 2 (cmd_etb_auto_calibrate_2)'
  - type: section
    props:
      title: TPS/PPS Limits
    children:
    - type: scalar-field
      id: tpserrordetectiontoolow
      props:
        label: TPS/PPS minimum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooLow
    - type: scalar-field
      id: tpserrordetectiontoohigh
      props:
        label: TPS/PPS maximum valid value
      bind:
        source: config
        field: tpsErrorDetectionTooHigh
    - type: scalar-field
      id: etbsplit
      props:
        label: TPS/PPS Error Detection Threshold
      bind:
        source: config
        field: etbSplit
  - type: section
    props:
      title: ETB Position Sensors special cases
    children:
    - type: enum-field
      id: usefordredundanttps
      props:
        label: Ford/Toyota redundant TPS mode
        options:
        - value: 0
          label: no
        - value: 1
          label: yes
      bind:
        source: config
        field: useFordRedundantTps
    - type: scalar-field
      id: tpssecondarymaximum
      props:
        label: Secondary TPS maximum
      bind:
        source: config
        field: tpsSecondaryMaximum
- type: section
  props:
    title: tpsGauges
