id: tpsTpsDialog.panel
description: TPS/TPS acceleration extra fuel
source:
  ini_dialog: tpsTpsDialog
  menu_path: Fuel › TPS Acceleration Enrichment / Wall Wetting AE › TPS/TPS acceleration extra fuel
children:
- type: section
  props:
    title: tpsTpsModeSelector
  children:
  - type: enum-field
    id: accelenrichmentmode
    props:
      options:
      - value: 0
        label: MS Adder
      - value: 1
        label: Percent Adder
      - value: 2
        label: MAP Prediction
      - value: 3
        label: INVALID
      label: Mode
    bind:
      source: config
      field: accelEnrichmentMode
- type: config-table
  id: tpstpsacceltbl
  props:
    title: TPS/TPS Acceleration Extra Fuel(ms)
    variant: table
  bind:
    source: config
    params:
      xBins: tpsTpsAccelFromRpmBins
      zBins: tpsTpsAccelTable
      yBins: tpsTpsAccelToRpmBins
