id: trigger_advanced.panel
description: Advanced Trigger
source:
  ini_dialog: trigger_advanced
  menu_path: Setup › Limits and protection › Advanced Trigger
children:
- type: scalar-field
  id: isphasesyncrequiredforignition
  props:
    label: Require cam/VVT sync for ignition
  bind:
    source: config
    field: isPhaseSyncRequiredForIgnition
- type: scalar-field
  id: camsynconsecondcrankrevolution
  props:
    label: Cam sync crank revolution
  bind:
    source: config
    field: camSyncOnSecondCrankRevolution
- type: scalar-field
  id: maxcamphaseresolverpm
  props:
    label: Maximum cam/VVT sync RPM
  bind:
    source: config
    field: maxCamPhaseResolveRpm
- type: scalar-field
  id: mapcamdetectionangleposition
  props:
    label: MAP readout angle
  bind:
    source: config
    field: mapCamDetectionAnglePosition
- type: scalar-field
  id: mapsyncthreshold
  props:
    label: MAP delta threshold
  bind:
    source: config
    field: mapSyncThreshold
- type: scalar-field
  id: usenoiselesstriggerdecoder
  props:
    label: Enable noise filtering
  bind:
    source: config
    field: useNoiselessTriggerDecoder
- type: section
  props:
    title: Console Logging
