id: uegoCan.panel
description: CAN O2 sensors
source:
  ini_dialog: uegoCan
  menu_path: CAN-bus › CAN O2 sensors
children:
- type: scalar-field
  id: support-for-aem-or-rusefi-can-uego
  props:
    label: Support for AEM or RusEFI CAN UEGO
  bind:
    source: config
    field: Support for AEM or RusEFI CAN UEGO
- type: enum-field
  id: enableaemxseries
  props:
    options:
    - value: 0
      label: 'false'
    - value: 1
      label: 'true'
    label: Enable CAN Wideband
  bind:
    source: config
    field: enableAemXSeries
- type: enum-field
  id: widebandonsecondbus
  props:
    label: Wideband CAN bus
    options:
    - value: 0
      label: CAN1
    - value: 1
      label: CAN2
  bind:
    source: config
    field: widebandOnSecondBus
- type: enum-field
  id: forceo2heating
  props:
    label: Force O2 sensor heating
    options:
    - value: 0
      label: no
    - value: 1
      label: yes
  bind:
    source: config
    field: forceO2Heating
- type: text
  props:
    variant: hint
    text: 'Кнопка: Update 2023 Firmware (cmd_wideband_firmare_update)'
