id: uegoCan.panel
description: CAN O2 sensors
source:
  ini_dialog: uegoCan
  menu_path: CAN-bus › CAN O2 sensors
children:
- type: scalar-field
  id: support-for-aem-or-rusefi-can-uego
  props:
    label: Support for AEM or RusEFI CAN UEGO
  bind:
    source: config
    field: Support for AEM or RusEFI CAN UEGO
- type: enum-field
  id: enableaemxseries
  props:
    options:
    - value: 0
      label: no
    - value: 1
      label: yes
    label: Enable CAN Wideband
  bind:
    source: config
    field: enableAemXSeries
- type: enum-field
  id: widebandonsecondbus
  props:
    label: Wideband CAN bus
    options:
    - value: 0
      label: CAN1
    - value: 1
      label: CAN2
  bind:
    source: config
    field: widebandOnSecondBus
- type: scalar-field
  id: afrexpaveragealpha
  props:
    label: Smoothing Factor
  bind:
    source: config
    field: afrExpAverageAlpha
- type: text
  props:
    text: Please use force heating only for testing.
    variant: hint
- type: text
  props:
    variant: hint
    text: Never keep enabled outside workshop.
- type: text
  props:
    text: This can damage your sensor.
    variant: hint
- type: enum-field
  id: forceo2heating
  props:
    label: Force O2 sensor heating
    options:
    - value: 0
      label: no
    - value: 1
      label: yes
  bind:
    source: config
    field: forceO2Heating
- type: text
  props:
    text: 'Кнопка: Restart all WBO (cmd_restart_widebands)'
    variant: hint
- type: text
  props:
    variant: hint
    text: 'Кнопка: Update 2023 Firmware from file (cmd_wideband_firmare_update_file)'
