id: vvtIntakeTargetDialog.panel
description: Intake VVT Target
source:
  ini_dialog: vvtIntakeTargetDialog
  menu_path: Advanced › Generic PWM › VVT intake target
children:
- type: config-table
  id: vvttable1tbl
  props:
    xBins: vvtTable1RpmBins
    zBins: vvtTable1
    title: Intake VVT closed loop Target
    variant: table
    yBins: vvtTable1LoadBins
- type: section
  props:
    title: VVT status & offset
  children:
  - type: scalar-field
    id: vvtoffsets1
    props:
      label: VVT offset bank 1 intake
    bind:
      source: config
      field: vvtOffsets1
