id: wwBetaCurves.panel
description: Wall wetting AE impact fraction
source:
  ini_dialog: wwBetaCurves
  menu_path: Fuel › Wall wetting AE › Impact fraction
children:
- type: text
  props:
    variant: hint
    text: Set a base impact fraction based on coolant temperature, and a multiplier based on MAP.
- type: curve
  id: wwbetacltcurve
  props:
    xLabel: coolant
    yBins: wwBetaCltValues
    yLabel: fraction
    title: Impact fraction vs. CLT
    xBins: wwCltBins
- type: curve
  id: wwbetamapcurve
  props:
    xLabel: MAP
    yBins: wwBetaMapValues
    title: Impact fraction vs. MAP
    yLabel: mult
    xBins: wwMapBins
