id: wwBetaCurves.panel
description: Wall wetting AE impact fraction
source:
  ini_dialog: wwBetaCurves
  menu_path: Fuel › Wall wetting AE › Impact fraction
children:
- type: text
  props:
    text: Set a base impact fraction based on coolant temperature, and a multiplier based on MAP.
    variant: hint
- type: config-table
  id: wwbetacltcurve
  props:
    variant: curve
    xBins: wwCltBins
    xLabel: coolant
    title: Impact fraction vs. CLT
    yLabel: fraction
    yBins: wwBetaCltValues
- type: config-table
  id: wwbetamapcurve
  props:
    title: Impact fraction vs. MAP
    xLabel: MAP
    variant: curve
    xBins: wwMapBins
    yBins: wwBetaMapValues
    yLabel: mult
