id: wwTauCurves.panel
description: Wall wetting AE evaporation time
source:
  ini_dialog: wwTauCurves
  menu_path: Fuel › Wall wetting AE › Evap time
children:
- type: text
  props:
    text: Set a base evaporation time based on coolant temperature, and a multiplier based on MAP.
    variant: hint
- type: config-table
  id: wwtaucltcurve
  props:
    xBins: wwCltBins
    xLabel: coolant
    title: Evap time vs. CLT
    yLabel: seconds
    yBins: wwTauCltValues
    variant: curve
- type: config-table
  id: wwtaumapcurve
  props:
    xLabel: MAP
    variant: curve
    xBins: wwMapBins
    yLabel: mult
    yBins: wwTauMapValues
    title: Evap time vs. MAP
