id: wwTauCurves.panel
description: Wall wetting AE evaporation time
source:
  ini_dialog: wwTauCurves
  menu_path: Fuel › Wall wetting AE › Evap time
children:
- type: text
  props:
    text: Set a base evaporation time based on coolant temperature, and a multiplier based on MAP.
    variant: hint
- type: curve
  id: wwtaucltcurve
  props:
    yBins: wwTauCltValues
    yLabel: seconds
    xBins: wwCltBins
    title: Evap time vs. CLT
    xLabel: coolant
- type: curve
  id: wwtaumapcurve
  props:
    xLabel: MAP
    title: Evap time vs. MAP
    yLabel: mult
    xBins: wwMapBins
    yBins: wwTauMapValues
