id: run.panel
description: Virtual Dyno run

children:
  - type: dyno
    id: dyno-main
    navSelectable: false
    props:
      height: 360
      dynoCharsPanel: dynochars.panel.yaml
    bind:
      source: outputChannels
      params:
        rpmField: RPMValue
        tpsField: TPSValue
