id: run.panel
description: Virtual Dyno run

children:
  - type: dyno
    id: dyno-main
    props:
      height: 360
      dynoCharsPanel: generated/dynochars.panel
    bind:
      source: outputChannels
      params:
        rpmField: RPMValue
        tpsField: TPSValue
