id: simulation.panel
description: Внутренняя стимуляция триггера (RPM)

children:
  - type: simulation
    id: ecu-simulator
    bind:
      source: outputChannels
      params:
        rpmField: RPMValue
